// config/index.js - Environment variables and constants
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Load .env.local overrides (auto-generated by Setup Wizard)
const envLocalPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(envLocalPath)) {
    require('dotenv').config({ path: envLocalPath, override: true });
}

// Auto-generate JWT_SECRET if missing (first run / fresh deploy)
let JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET) {
    JWT_SECRET = crypto.randomBytes(48).toString('base64url');
    console.warn('⚠️  JWT_SECRET no encontrado — generando uno automáticamente.');
    console.warn('   Se guardará en .env.local al completar el setup.');
}

module.exports = {
    PORT: process.env.PORT || 5001,
    JWT_SECRET,
    SETTINGS_ENCRYPTION_SECRET: process.env.SETTINGS_ENCRYPTION_SECRET || JWT_SECRET,
    EMAIL_USER: process.env.EMAIL_USER,
    EMAIL_PASS: process.env.EMAIL_PASS,
    EMAIL_HOST: process.env.EMAIL_HOST,
    EMAIL_PORT: process.env.EMAIL_PORT || 587,
    EMAIL_SERVICE: process.env.EMAIL_SERVICE || 'gmail',
    NODE_ENV: process.env.NODE_ENV || 'development',
    FRONTEND_URL: process.env.FRONTEND_URL,
    BASE_URL: process.env.BASE_URL,
    // Stripe configuration
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    // PayPal configuration
    PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
    PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
    PAYPAL_MODE: process.env.PAYPAL_MODE || 'sandbox', // 'sandbox' or 'live'

    // SaaS multi-tenant config (SAAS_MODE=false preserves single-tenant behavior)
    SAAS_MODE: process.env.SAAS_MODE || 'false',
    PLATFORM_DOMAIN: process.env.PLATFORM_DOMAIN || 'localhost',
    SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
    SUPER_ADMIN_SECRET: process.env.SUPER_ADMIN_SECRET,
    TRIAL_DAYS: parseInt(process.env.TRIAL_DAYS) || 14,
    REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
};
