/**
 * Rebuilds each demo seed file by:
 *  1. Querying app_settings from the matching live tenant
 *  2. Writing those as UPDATE statements into the settings section
 *  3. Preserving the original product DO $$ block verbatim
 *
 * Run: node backend/database/_rebuild_seeds.mjs
 */
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Settings that must NOT be baked into seed files
const EXCLUDE = new Set([
    'mailUser','mailHost','mailPort','mailUseTls','mailPass',
    'stripeSecretKey','stripePublishableKey',
    'paypalClientId','paypalClientSecret',
    'chatbotLlmApiKey','chatbotLlmCustomUrl',
    'mailFromName','mailFrom','mailTemplateHtml','chatbotSystemPrompt',
    'siteName','siteDomain',
]);

const SEEDS = [
    { file: 'seed-demo.sql',         schema: 'tenant_tienda1', label: 'Tech Azul (tienda1)' },
    { file: 'seed-demo-emerald.sql',  schema: 'tenant_tienda2', label: 'Esmeralda (tienda2)' },
    { file: 'seed-demo-rosa.sql',     schema: 'tenant_tienda3', label: 'Rosa (tienda3)' },
    { file: 'seed-demo-amber.sql',    schema: 'tenant_tienda4', label: 'Ámbar (tienda4)' },
    { file: 'seed-demo-carbon.sql',   schema: 'tenant_tienda5', label: 'Carbón (tienda5)' },
];

const NEWSLETTER_BLOCK = `
-- ---------------------------------------------------------------------------
-- 0. NEWSLETTER SUBSCRIBERS TABLE (safety for older installs)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT NOT NULL UNIQUE,
    subscribed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT 'home'
);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON newsletter_subscribers (email);
`;

/**
 * Fetch app_settings from a tenant schema as ready-to-use SQL UPDATE statements.
 * psql's quote_literal() handles all quoting safely inside the DB engine.
 */
function fetchSettingsSQL(schema, excludeList) {
    const excludeSQL = excludeList.map(e => `'${e}'`).join(',');
    // Build the UPDATE statements directly in SQL using quote_literal
    const sql = [
        `SELECT`,
        `  'UPDATE app_settings SET value = ' || quote_literal(value)`,
        `  || E'\\nWHERE id = ' || quote_literal(id) || ';'`,
        `FROM ${schema}.app_settings`,
        `WHERE id NOT IN (${excludeSQL})`,
        `ORDER BY id;`,
    ].join(' ');

    // Write SQL to a temp file inside the container then exec
    const result = execSync(
        `docker exec -e PGCLIENTENCODING=UTF8 eonsclover-db psql -U eonsclover -d eonsclover -t -A -c "${sql.replace(/"/g, '\\"')}"`,
        { encoding: 'buffer' }  // capture raw bytes, decode as UTF-8 ourselves
    );
    return Buffer.from(result).toString('utf8').trim();
}

for (const { file, schema, label } of SEEDS) {
    const filePath = path.join(__dirname, file);
    const original = fs.readFileSync(filePath, 'utf8');
    const lines = original.split('\n');

    // Find the products section: look for the "-- 2." or "SAMPLE PRODUCTS" comment,
    // or the first WITH/INSERT that targets the products table
    let splitIdx = -1;
    for (let i = 0; i < lines.length; i++) {
        const l = lines[i];
        if (/-- [0-9]+\..*PRODUCT/i.test(l) || /WITH p AS/i.test(l) || /INSERT INTO products/i.test(l)) {
            // Walk back to include the section separator comment
            let start = i;
            while (start > 0 && lines[start - 1].startsWith('--')) start--;
            splitIdx = start;
            break;
        }
    }

    if (splitIdx < 0) {
        console.error(`SKIP ${file} — products section not found`);
        continue;
    }

    const productsBlock = lines.slice(splitIdx).join('\n');

    // Fetch live settings from the tenant as SQL UPDATE statements
    const settingsSQL = fetchSettingsSQL(schema, [...EXCLUDE]);
    const lineCount = settingsSQL.split('\n').filter(l => l.startsWith('UPDATE')).length;

    const header = [
        `-- =============================================================================`,
        `-- Eonsclover — Demo Seed: ${label}`,
        `-- =============================================================================`,
        `-- Run AFTER seed.sql. Settings snapshotted from live tenant (${schema}).`,
        `-- NOTE: Runs in the tenant schema context (search_path already set).`,
        `-- =============================================================================`,
    ].join('\n');

    const newContent = [
        header,
        NEWSLETTER_BLOCK,
        `-- ---------------------------------------------------------------------------`,
        `-- 1. APP SETTINGS  (snapshotted from ${schema})`,
        `-- ---------------------------------------------------------------------------`,
        settingsSQL,
        ``,
        `-- ---------------------------------------------------------------------------`,
        `-- 2. DEMO PRODUCTS`,
        `-- ---------------------------------------------------------------------------`,
        productsBlock,
    ].join('\n');

    fs.writeFileSync(filePath, newContent, 'utf8');
    console.log(`✓ ${file}  (${lineCount} settings, products at line ${splitIdx + 1})`);
}

console.log('\nAll seed files rebuilt.');
