-- =============================================================================
-- TechStore — Complete Database Schema for Supabase (PostgreSQL)
-- =============================================================================
-- Run this in the Supabase SQL Editor to create all tables from scratch.
-- Safe to re-run: uses IF NOT EXISTS / OR REPLACE everywhere.
-- After this, run seed.sql for initial admin user and default settings.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. USERS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE,
    password    TEXT NOT NULL,                           -- bcrypt hash
    role        TEXT NOT NULL DEFAULT 'customer',        -- 'customer' | 'admin'
    phone       TEXT,
    street      TEXT,
    sector      TEXT,
    city        TEXT,
    country     TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    is_guest    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login  TIMESTAMPTZ
);

-- Index for email lookup (login, registration check)
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);


-- ---------------------------------------------------------------------------
-- 2. PRODUCTS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    price       NUMERIC(10, 2) NOT NULL DEFAULT 0,
    category    TEXT,
    stock       INTEGER NOT NULL DEFAULT 0,
    unit_type   TEXT NOT NULL DEFAULT 'unidad',        -- unidad, lb, kg, l, etc.
    image       TEXT,                                   -- legacy: full URL or old path
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backward compatibility for existing databases created before unit_type existed
ALTER TABLE products
ADD COLUMN IF NOT EXISTS unit_type TEXT NOT NULL DEFAULT 'unidad';

-- Flag to indicate this product uses variant-level stock/pricing
ALTER TABLE products
ADD COLUMN IF NOT EXISTS has_variants BOOLEAN NOT NULL DEFAULT FALSE;

-- Flag to hide product from public store (visible only in admin)
ALTER TABLE products
ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE;


-- ---------------------------------------------------------------------------
-- 3. PRODUCT IMAGES (gallery — multiple images per product)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    image_path  TEXT NOT NULL,                          -- Supabase Storage public URL
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images (product_id);


-- ---------------------------------------------------------------------------
-- 3b. PRODUCT ATTRIBUTE TYPES (global catalog: Color, Talla, Material…)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_attribute_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,                   -- 'Color', 'Talla', 'Material'
    display_type TEXT NOT NULL DEFAULT 'pill',          -- 'color_swatch' | 'pill' | 'dropdown'
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ---------------------------------------------------------------------------
-- 3c. PRODUCT VARIANTS (one row per unique combination, e.g. Rojo+M)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_variants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sku         TEXT,                                    -- optional SKU per variant
    price       NUMERIC(10, 2),                          -- NULL = inherit parent product price
    stock       INTEGER NOT NULL DEFAULT 0,
    image_url   TEXT,                                    -- variant-specific image (e.g. color swatch photo)
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_variants_product ON product_variants (product_id);


-- ---------------------------------------------------------------------------
-- 3d. PRODUCT VARIANT ATTRIBUTES (key-value pairs per variant)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_variant_attributes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id      BIGINT NOT NULL REFERENCES product_variants (id) ON DELETE CASCADE,
    attribute_type  TEXT NOT NULL,                        -- 'Color', 'Talla' (references type name)
    attribute_value TEXT NOT NULL,                        -- 'Rojo', 'M'
    color_hex       TEXT,                                 -- '#FF0000' — only for color_swatch attributes
    -- One value per attribute type per variant
    UNIQUE (variant_id, attribute_type)
);

-- Backward compatibility: add color_hex column if upgrading from older schema
ALTER TABLE product_variant_attributes ADD COLUMN IF NOT EXISTS color_hex TEXT;

CREATE INDEX IF NOT EXISTS idx_variant_attrs_variant ON product_variant_attributes (variant_id);


-- ---------------------------------------------------------------------------
-- 4. CART (server-side cart for authenticated users)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id  BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    variant_id  BIGINT REFERENCES product_variants (id) ON DELETE CASCADE,  -- NULL for non-variant products
    quantity    INTEGER NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- One cart entry per user+product+variant; upserted on add
    UNIQUE (user_id, product_id, variant_id)
);

-- Backward compatibility: add variant_id column if upgrading from older schema
ALTER TABLE cart ADD COLUMN IF NOT EXISTS variant_id BIGINT REFERENCES product_variants (id) ON DELETE CASCADE;

-- Migrate unique constraint from (user_id, product_id) to (user_id, product_id, variant_id)
-- Safe: only runs if old constraint exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cart_user_id_product_id_key'
    ) THEN
        ALTER TABLE cart DROP CONSTRAINT cart_user_id_product_id_key;
    END IF;
END;
$$;

-- Create new composite unique (idempotent via IF NOT EXISTS pattern)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cart_user_product_variant_unique'
    ) THEN
        ALTER TABLE cart ADD CONSTRAINT cart_user_product_variant_unique
            UNIQUE (user_id, product_id, variant_id);
    END IF;
END;
$$;

-- Partial unique index: prevent duplicate (user, product) when variant_id IS NULL
-- (SQL UNIQUE constraints treat NULL != NULL, so the constraint above won't catch it)
CREATE UNIQUE INDEX IF NOT EXISTS cart_user_product_no_variant_unique
    ON cart (user_id, product_id) WHERE variant_id IS NULL;


-- ---------------------------------------------------------------------------
-- 5. ORDERS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT REFERENCES users (id) ON DELETE SET NULL,  -- NULL for guest orders
    order_number            TEXT,                       -- human-friendly (generated after insert)
    total                   NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status                  TEXT NOT NULL DEFAULT 'pending_payment',
        -- Possible values: pending_payment, paid, to_ship, shipped,
        -- delivered, return, refund, cancelled, pending, processing
    payment_method          TEXT,                       -- cash, stripe, paypal, card, online
    shipping_address        TEXT,                       -- legacy: combined address string
    customer_name           TEXT,                       -- denormalized from user or guest input
    customer_email          TEXT,
    customer_phone          TEXT,
    shipping_street         TEXT,
    shipping_city           TEXT,
    shipping_postal_code    TEXT,
    shipping_sector         TEXT,
    shipping_cost           NUMERIC(10, 2),
    shipping_distance       NUMERIC,
    shipping_coordinates    TEXT,                       -- JSON-stringified { lat, lng }
    internal_notes          TEXT,                       -- admin-only notes
    carrier                 TEXT,                       -- shipping carrier name
    tracking_number         TEXT,                       -- shipment tracking ID
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_user        ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status      ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_number      ON orders (order_number);


-- ---------------------------------------------------------------------------
-- 6. ORDER ITEMS (line items within an order)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id          BIGINT REFERENCES products (id) ON DELETE SET NULL,  -- nullable: product may be deleted
    variant_id          BIGINT,                                              -- snapshot: variant may be deleted
    variant_attributes  JSONB,                                               -- snapshot: {"Color":"Rojo","Talla":"M"}
    quantity            INTEGER NOT NULL DEFAULT 1,
    price               NUMERIC(10, 2) NOT NULL DEFAULT 0                   -- snapshot at time of purchase
);

-- Backward compatibility: add variant columns if upgrading from older schema
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variant_id BIGINT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variant_attributes JSONB;

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);


-- ---------------------------------------------------------------------------
-- 7. VERIFICATION CODES (email verification / password reset)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS verification_codes (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email       TEXT NOT NULL,
    code        TEXT NOT NULL,                          -- 6-digit string
    purpose     TEXT NOT NULL,                          -- register, password_reset, general
    expires_at  TIMESTAMPTZ NOT NULL,                   -- typically NOW() + 10 min
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_verification_email ON verification_codes (email, purpose);


-- ---------------------------------------------------------------------------
-- 8. APP SETTINGS (key-value store for site configuration)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_settings (
    id          TEXT PRIMARY KEY,                       -- setting key (e.g., 'siteName')
    value       TEXT,                                   -- always stored as string
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ---------------------------------------------------------------------------
-- 9. TOKEN BLACKLIST (revoked JWT sessions)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS token_blacklist (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    token_hash  TEXT NOT NULL,                          -- SHA-256 of the JWT
    session_id  TEXT,                                   -- session identifier from JWT payload
    user_id     BIGINT REFERENCES users (id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ NOT NULL,                   -- matches original JWT expiry
    revoked_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reason      TEXT DEFAULT 'logout'                   -- logout, password_change, admin_revoke
);

CREATE INDEX IF NOT EXISTS idx_token_blacklist_hash ON token_blacklist (token_hash);
CREATE INDEX IF NOT EXISTS idx_token_blacklist_expires ON token_blacklist (expires_at);


-- ===========================================================================
-- RPC FUNCTIONS — Atomic stock operations (called via supabase.rpc())
-- ===========================================================================

-- Decrement stock only if enough is available (prevents overselling)
CREATE OR REPLACE FUNCTION decrement_stock_if_available(p_product_id BIGINT, p_quantity INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE products
    SET stock = stock - p_quantity,
        updated_at = NOW()
    WHERE id = p_product_id
      AND stock >= p_quantity;

    RETURN FOUND;
END;
$$;

-- Increment stock (used for order cancellations / returns)
CREATE OR REPLACE FUNCTION increment_stock(p_product_id BIGINT, p_quantity INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE products
    SET stock = stock + p_quantity,
        updated_at = NOW()
    WHERE id = p_product_id;

    RETURN FOUND;
END;
$$;


-- Decrement VARIANT stock only if enough is available (prevents overselling)
CREATE OR REPLACE FUNCTION decrement_variant_stock(p_variant_id BIGINT, p_quantity INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE product_variants
    SET stock = stock - p_quantity,
        updated_at = NOW()
    WHERE id = p_variant_id
      AND stock >= p_quantity
      AND is_active = TRUE;

    RETURN FOUND;
END;
$$;

-- Increment VARIANT stock (used for order cancellations / returns)
CREATE OR REPLACE FUNCTION increment_variant_stock(p_variant_id BIGINT, p_quantity INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE product_variants
    SET stock = stock + p_quantity,
        updated_at = NOW()
    WHERE id = p_variant_id;

    RETURN FOUND;
END;
$$;


-- ===========================================================================
-- SUPABASE STORAGE — Bucket for product images (Supabase-only)
-- ===========================================================================
-- Only runs when the 'storage' schema exists (Supabase environment).
-- On plain PostgreSQL (Docker), images are stored on the filesystem.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage') THEN
    -- Create "products" bucket (public read)
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('products', 'products', true)
    ON CONFLICT (id) DO NOTHING;

    -- Policies: public read + full CRUD on products bucket
    EXECUTE 'DROP POLICY IF EXISTS "Public read products" ON storage.objects';
    EXECUTE 'CREATE POLICY "Public read products" ON storage.objects FOR SELECT USING (bucket_id = ''products'')';

    EXECUTE 'DROP POLICY IF EXISTS "Anon upload products" ON storage.objects';
    EXECUTE 'CREATE POLICY "Anon upload products" ON storage.objects FOR INSERT WITH CHECK (bucket_id = ''products'')';

    EXECUTE 'DROP POLICY IF EXISTS "Anon update products" ON storage.objects';
    EXECUTE 'CREATE POLICY "Anon update products" ON storage.objects FOR UPDATE USING (bucket_id = ''products'')';

    EXECUTE 'DROP POLICY IF EXISTS "Anon delete products" ON storage.objects';
    EXECUTE 'CREATE POLICY "Anon delete products" ON storage.objects FOR DELETE USING (bucket_id = ''products'')';

    RAISE NOTICE 'Supabase storage bucket + policies created';
  ELSE
    RAISE NOTICE 'Supabase storage schema not found — skipping (filesystem storage mode)';
  END IF;
END;
$$;
