-- =============================================================================
-- Eonsclover — Demo Seed: Esmeralda (tienda2)
-- =============================================================================
-- Run AFTER seed.sql. Settings snapshotted from live tenant (tenant_tienda2).
-- NOTE: Runs in the tenant schema context (search_path already set).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. NEWSLETTER SUBSCRIBERS TABLE (safety for older installs)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT NOT NULL UNIQUE,
    subscribed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT 'home'
);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON newsletter_subscribers (email);

-- ---------------------------------------------------------------------------
-- 1. APP SETTINGS  (snapshotted from tenant_tienda2)
-- ---------------------------------------------------------------------------
UPDATE app_settings SET value = '#f59e0b'
WHERE id = 'accentColor';
UPDATE app_settings SET value = '#619e73'
WHERE id = 'backgroundColor';
UPDATE app_settings SET value = '{"useDefault":false,"categories":[{"id":"todos","name":"Todos","icon":"🌿","slug":"todos","image":""},{"id":"suplementos","name":"Suplementos","icon":"💊","slug":"Suplementos","image":""},{"id":"alimentos","name":"Alimentos Orgánicos","icon":"🥦","slug":"Alimentos Orgánicos","image":""},{"id":"fitness","name":"Fitness","icon":"🏋️","slug":"Fitness","image":""},{"id":"cuidado","name":"Cuidado Natural","icon":"🌱","slug":"Cuidado Natural","image":""},{"id":"infusiones","name":"Infusiones","icon":"🍵","slug":"Infusiones","image":""}],"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"","cardBackground":"","cardBorderColor":"","cardShadow":"","hoverBackground":"","hoverBorderColor":"","hoverShadow":"","hoverTitleColor":"","activeBackground":"","activeBorderColor":"","activeShadow":"","titleColor":"","activeTitleColor":"","titleSize":"","titleWeight":"","titleTransform":"","titleLetterSpacing":"","iconSize":""}}'
WHERE id = 'categoryFiltersConfig';
UPDATE app_settings SET value = '#059669'
WHERE id = 'chatbotColor';
UPDATE app_settings SET value = 'false'
WHERE id = 'chatbotEnabled';
UPDATE app_settings SET value = '¡Hola! 👋 Soy el asistente de Eonsclover. ¿En qué puedo ayudarte?'
WHERE id = 'chatbotGreeting';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmModel';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmProvider';
UPDATE app_settings SET value = '50'
WHERE id = 'chatbotMaxMessages';
UPDATE app_settings SET value = '500'
WHERE id = 'chatbotMaxTokens';
UPDATE app_settings SET value = 'helpful'
WHERE id = 'chatbotPersonality';
UPDATE app_settings SET value = 'Escribe tu mensaje...'
WHERE id = 'chatbotPlaceholder';
UPDATE app_settings SET value = '0.7'
WHERE id = 'chatbotTemperature';
UPDATE app_settings SET value = 'normal'
WHERE id = 'chatbotVerbosity';
UPDATE app_settings SET value = ''
WHERE id = 'contactAddress';
UPDATE app_settings SET value = 'Eonsclover'
WHERE id = 'contactCompany';
UPDATE app_settings SET value = ''
WHERE id = 'contactEmail';
UPDATE app_settings SET value = 'Lunes a Viernes: 9:00 AM - 6:00 PM'
WHERE id = 'contactHours';
UPDATE app_settings SET value = ''
WHERE id = 'contactPhone';
UPDATE app_settings SET value = '¿Tienes preguntas? Estamos aquí para ayudarte'
WHERE id = 'contactSubtitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactSupportLine';
UPDATE app_settings SET value = 'Contáctanos'
WHERE id = 'contactTitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactWhatsapp';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailInvoiceAutoSend';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailOrderConfirmation';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailPasswordReset';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyGuestCheckout';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyRegistration';
UPDATE app_settings SET value = 'system-ui, sans-serif'
WHERE id = 'fontFamily';
UPDATE app_settings SET value = '{"brandMessage":"Tu tienda de confianza para todos los dispositivos electrónicos y accesorios.","quickLinksTitle":"Enlaces Rápidos","quickLinks":[{"label":"Inicio","href":"/","enabled":true},{"label":"Productos","href":"/tienda","enabled":true},{"label":"Ofertas","href":"/tienda?promo=1","enabled":true},{"label":"Sobre Nosotros","href":"/contacto","enabled":true}],"supportTitle":"Atención al Cliente","supportLinks":[{"label":"Contáctanos","href":"/contacto","enabled":true},{"label":"Devoluciones","href":"/contacto","enabled":true},{"label":"Preguntas Frecuentes","href":"/contacto","enabled":true},{"label":"Estado del Pedido","href":"/orders","enabled":true}],"socialTitle":"Síguenos","socialLinks":[{"icon":"📘","href":"","enabled":true},{"icon":"📱","href":"","enabled":true},{"icon":"📷","href":"","enabled":true},{"icon":"🐦","href":"","enabled":true}],"copyrightText":"© 2026 Eonsclover. Todos los derechos reservados."}'
WHERE id = 'footerConfig';
UPDATE app_settings SET value = '50000'
WHERE id = 'freeShippingThreshold';
UPDATE app_settings SET value = '#059669'
WHERE id = 'headerBgColor';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'headerButtonColor';
UPDATE app_settings SET value = '#059669'
WHERE id = 'headerButtonTextColor';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'headerTextColor';
UPDATE app_settings SET value = '100'
WHERE id = 'headerTransparency';
UPDATE app_settings SET value = '/storage/products/seed-emerald-banner.jpg'
WHERE id = 'heroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'heroBannerOpacity';
UPDATE app_settings SET value = 'right'
WHERE id = 'heroBannerPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'heroBannerPositionY';
UPDATE app_settings SET value = '260'
WHERE id = 'heroBannerSize';
UPDATE app_settings SET value = 'Descubre nuestra selección de suplementos naturales, alimentos orgánicos certificados y todo lo que necesitas para llevar un estilo de vida saludable.'
WHERE id = 'heroDescription';
UPDATE app_settings SET value = '1.05'
WHERE id = 'heroDescriptionSize';
UPDATE app_settings SET value = '420'
WHERE id = 'heroHeight';
UPDATE app_settings SET value = '/storage/products/seed-emerald-hero-bg.jpg'
WHERE id = 'heroImage';
UPDATE app_settings SET value = '50'
WHERE id = 'heroImageBgX';
UPDATE app_settings SET value = '50'
WHERE id = 'heroImageBgY';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageBgZoom';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageWidth';
UPDATE app_settings SET value = '0.40'
WHERE id = 'heroOverlayOpacity';
UPDATE app_settings SET value = 'left'
WHERE id = 'heroPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'heroPositionY';
UPDATE app_settings SET value = 'Explorar Productos'
WHERE id = 'heroPrimaryBtn';
UPDATE app_settings SET value = 'Ver Orgánicos'
WHERE id = 'heroSecondaryBtn';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'heroTextColor';
UPDATE app_settings SET value = '0'
WHERE id = 'heroTextPaddingX';
UPDATE app_settings SET value = '0'
WHERE id = 'heroTextPaddingY';
UPDATE app_settings SET value = 'Salud, Bienestar y Vida Orgánica'
WHERE id = 'heroTitle';
UPDATE app_settings SET value = '2.1'
WHERE id = 'heroTitleSize';
UPDATE app_settings SET value = '{}'
WHERE id = 'invoicePdfConfig';
UPDATE app_settings SET value = '{"enabled":false,"route":"/landing","pageTitle":"Ofertas Especiales","templateId":"modern-minimal","globalStyles":{"fontFamily":"inherit","darkColor":"var(--secondary-color)","lightColor":"var(--background-color)","accentColor":"var(--primary-color)","accentHoverColor":"var(--primary-hover)","textColor":"var(--text-color)","textLightColor":"var(--text-color)","headingColor":"var(--text-color)","maxWidth":1200,"sectionPadding":80,"sectionPaddingMobile":48},"sections":[{"id":"hero","type":"hero","enabled":true,"data":{"layout":"text-left","title":"La Mejor Tecnología a Tu Alcance","subtitle":"Descubre productos premium con la mejor calidad y precios incomparables.","ctaText":"Comprar Ahora","ctaLink":"/","image":"","badgeText":"","badgeColor":"var(--primary-color)"},"styles":{"bgColor":"var(--secondary-color)","bgGradient":"","bgImage":"","bgOverlayOpacity":0.5,"textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","minHeight":500}},{"id":"valueProposition","type":"valueProposition","enabled":true,"data":{"label":"Nuestras Ventajas","title":"¿Por qué elegirnos?","description":"Ofrecemos la mejor experiencia de compra con beneficios exclusivos para ti.","points":[{"icon":"🚚","iconImage":"","title":"Envío Gratis","description":""},{"icon":"🛡️","iconImage":"","title":"Garantía Total","description":""},{"icon":"💰","iconImage":"","title":"Mejor Precio","description":""},{"icon":"🔒","iconImage":"","title":"Pago Seguro","description":""}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","iconBgColor":"var(--background-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.08)"}},{"id":"productHighlight","type":"productHighlight","enabled":true,"data":{"layout":"image-left","label":"Propuesta Única","title":"Producto Destacado","description":"Descripción del producto y sus beneficios clave para el cliente. Enfócate en el valor que aporta.","ctaText":"Ver Más","ctaLink":"/","image":""},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"trustBanner","type":"trustBanner","enabled":true,"data":{"title":"Valorado por nuestros clientes","subtitle":"Miles de clientes satisfechos confían en nosotros cada día."},"styles":{"bgColor":"var(--primary-color)","textColor":"var(--background-color)"}},{"id":"featuredProduct","type":"featuredProduct","enabled":true,"data":{"label":"El mejor producto","productName":"Audífonos Inalámbricos Pro","productId":null,"image":"","specs":[{"key":"Tipo","value":"Inalámbrico"},{"key":"Batería","value":"40 horas"},{"key":"Cancelación de ruido","value":"Sí"},{"key":"Peso","value":"250g"}],"description":"Sonido premium con cancelación de ruido activa. La mejor experiencia auditiva.","originalPrice":158,"salePrice":118.99,"badgeText":"OFERTA","ctaText":"Comprar Ahora","ctaLink":"/"},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","priceSaleColor":"var(--primary-color)","priceOriginalColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","specsDotColor":"var(--secondary-color)"}},{"id":"howItWorks","type":"howItWorks","enabled":true,"data":{"title":"¿Cómo Funciona?","steps":[{"number":"1","title":"Explora","description":"Navega nuestra colección de productos tecnológicos."},{"number":"2","title":"Selecciona","description":"Elige tu producto favorito y agrégalo al carrito."},{"number":"3","title":"Recibe","description":"Completa tu compra y recíbelo en la puerta de tu casa."}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","stepNumberBg":"var(--primary-color)","stepNumberColor":"var(--background-color)","stepCardBg":"var(--background-color)","stepCardBorder":"var(--secondary-color)"}},{"id":"productShowcase","type":"productShowcase","enabled":true,"data":{"title":"Productos Destacados","subtitle":"Descubre nuestras mejores ofertas en tecnología.","products":[{"productId":null,"name":"Laptop Gaming","description":"Alto rendimiento para gaming profesional.","category":"Laptops","image":"","features":["Procesador ultra rápido","Gráficos inmersivos","Batería duradera"],"originalPrice":1189,"salePrice":899,"badgeText":"30% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Audífonos Wireless","description":"Sonido cristalino con cancelación de ruido.","category":"Audio","image":"","features":["Cancelación de ruido","Batería extendida","Audio superior"],"originalPrice":199,"salePrice":59.7,"badgeText":"70% OFF","badgeColor":"var(--accent-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Teclado Mecánico","description":"Teclas responsivas para gaming y productividad.","category":"Periféricos","image":"","features":["RGB backlight","Switches resistentes","Diseño ergonómico"],"originalPrice":129,"salePrice":89,"badgeText":"31% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Monitor 4K","description":"Visuales ultra HD con colores vívidos.","category":"Monitores","image":"","features":["Alta tasa de refresco","Amplia gama de colores","Soporte ajustable"],"originalPrice":499,"salePrice":399.2,"badgeText":"20% OFF","badgeColor":"var(--secondary-color)","ctaText":"Ver Producto","ctaLink":"/"}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 4px 12px rgba(0,0,0,0.1)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"testimonials","type":"testimonials","enabled":true,"data":{"title":"Lo que dicen nuestros clientes","subtitle":"Opiniones reales de compradores verificados.","items":[{"quote":"Excelente calidad y servicio rápido. Totalmente recomendado.","author":"María García","avatar":"","rating":5},{"quote":"Los mejores precios del mercado y atención personalizada.","author":"Carlos Rodríguez","avatar":"","rating":5},{"quote":"Compra segura y envío rápido. Volveré a comprar sin duda.","author":"Ana Martínez","avatar":"","rating":4},{"quote":"El mejor sonido que he escuchado. Producto increíble.","author":"Pedro López","avatar":"","rating":5}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.06)","quoteColor":"var(--text-color)","authorColor":"var(--text-color)","starColor":"var(--accent-color)"}},{"id":"leadCapture","type":"leadCapture","enabled":false,"data":{"title":"¡Obtén tu descuento exclusivo!","description":"Completa el formulario y recibe códigos de descuento directamente en tu email.","aboutText":"Somos un equipo apasionado que ofrece tecnología de primera calidad a precios imbatibles.","fields":["name","email"],"submitText":"Enviar","successMessage":"¡Gracias! Revisa tu correo para tu código de descuento."},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","inputBgColor":"var(--background-color)","inputBorderColor":"var(--secondary-color)","submitBgColor":"var(--primary-color)","submitTextColor":"var(--background-color)"}},{"id":"finalCta","type":"finalCta","enabled":true,"data":{"title":"¿Qué esperas?","subtitle":"Aprovecha nuestras ofertas antes de que se agoten.","ctaText":"Ir a la Tienda","ctaLink":"/"},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}}]}'
WHERE id = 'landingPageConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'maintenanceMode';
UPDATE app_settings SET value = '{"mapEnabled":true,"shippingCalcEnabled":true,"storeLocation":{"lat":18.462673,"lng":-69.936051},"shippingZones":[{"maxDistance":5,"price":100,"label":"Zona 1"},{"maxDistance":10,"price":150,"label":"Zona 2"},{"maxDistance":20,"price":200,"label":"Zona 3"},{"maxDistance":50,"price":350,"label":"Zona 4"},{"maxDistance":9999,"price":600,"label":"Zona 5"}]}'
WHERE id = 'mapConfig';
UPDATE app_settings SET value = '{"showHomeLink":true,"showStoreLink":true}'
WHERE id = 'navigationConfig';
UPDATE app_settings SET value = '{"enabled":false,"title":"Únete a Nuestra Newsletter","text":"Recibe las últimas noticias sobre tecnología y ofertas exclusivas directamente en tu correo.","placeholder":"Tu correo electrónico","buttonText":"Suscribirse"}'
WHERE id = 'newsletterConfig';
UPDATE app_settings SET value = '{"cash":{"enabled":true,"name":"Pago Contra Entrega","description":"Paga en efectivo cuando recibas tu pedido","icon":"💵","order":1},"transfer":{"enabled":true,"name":"Transferencia Bancaria","description":"Transferencia o depósito bancario","icon":"🏦","order":2,"bankName":"","bankHolder":"","bankAccount":"","transferNote":""},"stripe":{"enabled":true,"name":"Tarjeta de Crédito/Débito","description":"Visa, MasterCard, American Express","icon":"💳","order":3,"testMode":true},"paypal":{"enabled":false,"name":"PayPal","description":"Paga con tu cuenta PayPal","icon":"🅿️","order":4}}'
WHERE id = 'paymentMethodsConfig';
UPDATE app_settings SET value = '#059669'
WHERE id = 'primaryColor';
UPDATE app_settings SET value = '{"useDefault":true,"layout":{"orientation":"vertical","columnsMobile":2,"columnsTablet":3,"columnsDesktop":4,"columnsWide":5},"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"","borderWidth":"","borderStyle":"","borderColor":"","background":"","shadow":"","titleColor":"","titleSize":"","titleWeight":"","priceColor":"","priceSize":"","priceWeight":"","descriptionColor":"","descriptionSize":"","categoryColor":"","categorySize":"","buttonBg":"","buttonText":"","buttonRadius":"","buttonBorder":"","buttonShadow":""},"currency":"DOP"}'
WHERE id = 'productCardConfig';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'productDetailHeroBannerOpacity';
UPDATE app_settings SET value = 'right'
WHERE id = 'productDetailHeroBannerPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'productDetailHeroBannerPositionY';
UPDATE app_settings SET value = '120'
WHERE id = 'productDetailHeroBannerSize';
UPDATE app_settings SET value = '200'
WHERE id = 'productDetailHeroHeight';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroImage';
UPDATE app_settings SET value = '40'
WHERE id = 'productDetailHeroOverlayOpacity';
UPDATE app_settings SET value = 'false'
WHERE id = 'productDetailUseHomeHero';
UPDATE app_settings SET value = 'Ver Oferta'
WHERE id = 'promoButtonText';
UPDATE app_settings SET value = '/storage/products/seed-emerald-promo.jpg'
WHERE id = 'promoImage';
UPDATE app_settings SET value = '7'
WHERE id = 'promoProductId';
UPDATE app_settings SET value = '🌿 ¡Semana Verde! Obtén un 20% de descuento en todos los suplementos certificados orgánicos al comprar dos o más productos.'
WHERE id = 'promoText';
UPDATE app_settings SET value = '¡Oferta Especial del Mes!'
WHERE id = 'promoTitle';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'searchBarConfig';
UPDATE app_settings SET value = '#0d9488'
WHERE id = 'secondaryColor';
UPDATE app_settings SET value = '{}'
WHERE id = 'seoConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'shippingSlipEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'showPromotionBanner';
UPDATE app_settings SET value = '🛍️'
WHERE id = 'siteIcon';
UPDATE app_settings SET value = ''
WHERE id = 'siteLogo';
UPDATE app_settings SET value = '40'
WHERE id = 'siteLogoSize';
UPDATE app_settings SET value = ''
WHERE id = 'siteNameImage';
UPDATE app_settings SET value = '38'
WHERE id = 'siteNameImageSize';
UPDATE app_settings SET value = ''
WHERE id = 'storeAddress';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'storeModuleConfig';
UPDATE app_settings SET value = ''
WHERE id = 'storePhone';
UPDATE app_settings SET value = '#1e293b'
WHERE id = 'textColor';
UPDATE app_settings SET value = '{"enabled":true,"sectionTitle":"¿Por Qué Elegirnos?","items":[{"icon":"🚚","title":"Envío Gratis","text":"En todos tus pedidos superiores a $50"},{"icon":"⚡","title":"Garantía Extendida","text":"12 meses adicionales en todos nuestros productos"},{"icon":"🔒","title":"Pago Seguro","text":"Todas las transacciones son 100% seguras"}]}'
WHERE id = 'whyChooseUsConfig';

-- ---------------------------------------------------------------------------
-- 2. DEMO PRODUCTS
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- 2. SAMPLE PRODUCTS — health & wellness store
-- ---------------------------------------------------------------------------

-- ── Suplementos ──────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Colágeno Marino Hidrolizado Premium 300g',
        '<p>El suplemento de belleza y articulaciones más completo del mercado. Con <strong>10 g de colágeno marino tipo I y III</strong> por porción, junto con vitamina C y ácido hialurónico para una absorción máxima.</p>
<ul>
  <li><strong>Colágeno marino tipo I y III</strong>: péptidos ultrahidrolizados de peces de aguas frías — máxima biodisponibilidad</li>
  <li><strong>Vitamina C añadida</strong>: esencial para la síntesis natural de colágeno en la piel y articulaciones</li>
  <li><strong>Ácido hialurónico 50 mg</strong>: hidratación profunda de la piel desde adentro hacia afuera</li>
  <li><strong>Biotina + zinc</strong>: refuerzan cabello, uñas y la barrera cutánea</li>
  <li><strong>Sin sabor, sin azúcar</strong>: se disuelve perfectamente en agua, jugo o smoothies</li>
  <li><strong>30 porciones</strong>: suministro completo de un mes para resultados visibles</li>
</ul>
<p>Resultados visibles en 4-8 semanas: piel más firme, articulaciones más flexibles y cabello más fuerte. Libre de gluten, sin OMG. Fabricado en planta certificada GMP.</p>',
        39.99,
        'Suplementos',
        60,
        '/storage/products/seed-emerald-supplement-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-supplement-1.jpg'),
    ('/storage/products/seed-emerald-supplement-2.jpg'),
    ('/storage/products/seed-emerald-promo.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Proteína Vegana de Guisante y Arroz 1kg',
        '<p>La proteína plant-based más completa para atletas y deportistas conscientes. <strong>25 g de proteína vegetal por porción</strong> con todos los aminoácidos esenciales en perfecto equilibrio.</p>
<ul>
  <li><strong>Blend guisante + arroz integral</strong>: perfil de aminoácidos completo comparable a la whey — sin lactosa, sin soja</li>
  <li><strong>25 g de proteína por porción</strong>: ideal para recuperación muscular y ganancia de masa sin restricciones dietéticas</li>
  <li><strong>Digestión fácil</strong>: enzimas digestivas añadidas (bromelina + papaína) para minimizar el malestar intestinal</li>
  <li><strong>Sabor chocolate negro</strong>: endulzado con stevia pura — sin azúcar añadida, sin edulcorantes artificiales</li>
  <li><strong>Sin alérgenos comunes</strong>: libre de gluten, lactosa, soja, nueces y OMG</li>
  <li><strong>33 porciones</strong>: bolsa con cierre zip reutilizable para conservar frescura</li>
</ul>
<p>Certificado orgánico y vegano. Ideal para batidos post-entreno, overnight oats, pancakes proteicos y recetas saludables.</p>',
        49.99,
        'Suplementos',
        45,
        '/storage/products/seed-emerald-protein-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-protein-1.jpg'),
    ('/storage/products/seed-emerald-protein-2.jpg'),
    ('/storage/products/seed-emerald-hero-bg.jpg')
) AS imgs(img);

-- ── Alimentos Orgánicos ───────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Pack Verduras Orgánicas Certificadas de Temporada',
        '<p>Una caja cuidadosamente seleccionada con las mejores <strong>verduras orgánicas de temporada</strong> directamente del campo a tu mesa. Todo cultivado sin pesticidas ni fertilizantes químicos.</p>
<ul>
  <li><strong>6-8 variedades frescas</strong>: tomates cherry, espinacas, zanahorias, zucchini, pimientos y más según temporada</li>
  <li><strong>Certificación orgánica</strong>: todos los productores cuentan con sello USDA Organic o equivalente local</li>
  <li><strong>Recogida el día anterior</strong>: garantiza la máxima frescura y contenido nutricional en cada entrega</li>
  <li><strong>Productores locales</strong>: apoyamos granjas familiares dentro de un radio de 100 km</li>
  <li><strong>Caja biodegradable</strong>: empaque 100% compostable, cero plástico de un solo uso</li>
  <li><strong>Recetas incluidas</strong>: tarjeta con 3 recetas para aprovechar al máximo los productos del pack</li>
</ul>
<p>Pack estándar: aprox. 3.5 kg de verduras surtidas. Disponible en suscripción semanal o quincenal con descuento del 10%.</p>',
        24.99,
        'Alimentos Orgánicos',
        30,
        '/storage/products/seed-emerald-veggies-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-veggies-1.jpg'),
    ('/storage/products/seed-emerald-veggies-2.jpg'),
    ('/storage/products/seed-emerald-promo.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Aceite de Oliva Extra Virgen Orgánico 500ml',
        '<p>Un aceite de oliva de categoría superior, extraído en frío de aceitunas <strong>Arbequina y Picual cultivadas orgánicamente</strong> en pequeñas fincas familiares del Mediterráneo.</p>
<ul>
  <li><strong>Primera prensada en frío</strong>: extracción mecánica sin solventes — preserva todos los polifenoles y vitamina E</li>
  <li><strong>Acidez ≤ 0.3%</strong>: supera el estándar de 0.8% exigido para la categoría extra virgen</li>
  <li><strong>Certificado orgánico USDA + EU Bio</strong>: sin pesticidas, herbicidas ni fertilizantes sintéticos</li>
  <li><strong>Alto en antioxidantes</strong>: oleocanthal, oleuropeína y escualeno para beneficios cardiovasculares</li>
  <li><strong>Botella de vidrio oscuro</strong>: protege el aceite de la oxidación por luz UV</li>
  <li><strong>Cosecha de temporada</strong>: etiquetado con año de cosecha para máxima trazabilidad</li>
</ul>
<p>Ideal en crudo para ensaladas, tostadas y salsas. También apto para cocinar a temperatura media. 500 ml / 16.9 fl oz.</p>',
        19.99,
        'Alimentos Orgánicos',
        80,
        '/storage/products/seed-emerald-oliveoil-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-oliveoil-1.jpg'),
    ('/storage/products/seed-emerald-veggies-1.jpg'),
    ('/storage/products/seed-emerald-veggies-2.jpg')
) AS imgs(img);

-- ── Fitness ───────────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Esterilla de Yoga Antideslizante TPE 6mm',
        '<p>La esterilla que no se mueve contigo. Fabricada en <strong>TPE ecológico de doble capa</strong>, ofrece el agarre, la amortiguación y la alineación perfecta para cualquier práctica de yoga o pilates.</p>
<ul>
  <li><strong>Material TPE ecológico</strong>: libre de PVC, látex y metales pesados — biodegradable al final de su vida útil</li>
  <li><strong>6 mm de espesor</strong>: equilibrio ideal entre agarre y amortiguación para rodillas y articulaciones</li>
  <li><strong>Textura antideslizante doble cara</strong>: alineación de puntos grabados para posturas correctas</li>
  <li><strong>Superficie de humedad absorbente</strong>: mantiene el agarre incluso en sesiones intensas</li>
  <li><strong>Dimensiones</strong>: 183 × 61 cm — apta para cualquier estatura</li>
  <li><strong>Peso</strong>: 1.1 kg con correa de transporte incluida — llévala al estudio fácilmente</li>
</ul>
<p>Disponible en: Verde Bosque (este), Azul Pacífico, Lavanda y Gris Pizarra. Limpia con paño húmedo o lávala a mano con jabón neutro.</p>',
        34.99,
        'Fitness',
        55,
        '/storage/products/seed-emerald-yoga-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-yoga-1.jpg'),
    ('/storage/products/seed-emerald-yoga-2.jpg'),
    ('/storage/products/seed-emerald-bands-1.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Set de Bandas Elásticas de Resistencia 5 Niveles',
        '<p>Entrena donde quieras con el set de bandas más completo del mercado. <strong>5 niveles de resistencia</strong> desde 2 hasta 45 kg para principiantes y atletas avanzados por igual.</p>
<ul>
  <li><strong>5 bandas de latex natural</strong>: Amarilla (2-4 kg), Verde (4-7 kg), Azul (7-14 kg), Roja (14-22 kg), Negra (22-45 kg)</li>
  <li><strong>Latex natural premium</strong>: mayor durabilidad y elasticidad que las bandas sintéticas — resisten más de 1000 repeticiones</li>
  <li><strong>Versatilidad total</strong>: sentadillas, press, remo, extensiones, asistencia en dominadas y más de 50 ejercicios</li>
  <li><strong>Sin látex alergénico</strong>: formulación especial apta para personas con sensibilidad</li>
  <li><strong>Set completo</strong>: 5 bandas + bolsa de malla transpirable + guía de ejercicios en PDF</li>
  <li><strong>Portátil y ligero</strong>: todo el set pesa 500 g y cabe en cualquier mochila</li>
</ul>
<p>Ideal para home gym, viajes o uso en el gimnasio como complemento de pesas. Garantía de 1 año contra roturas.</p>',
        22.99,
        'Fitness',
        70,
        '/storage/products/seed-emerald-bands-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-bands-1.jpg'),
    ('/storage/products/seed-emerald-bands-2.jpg'),
    ('/storage/products/seed-emerald-yoga-1.jpg')
) AS imgs(img);

-- ── Cuidado Natural ───────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Jabón Natural de Aloe Vera y Carbón Activado',
        '<p>Un jabón artesanal <strong>100% natural</strong> elaborado en frío con aloe vera orgánico y carbón activado de bambú. Limpia profundamente los poros sin agredir la barrera natural de la piel.</p>
<ul>
  <li><strong>Aloe vera orgánico al 30%</strong>: calma, hidrata y regenera — ideal para piel sensible, seca o con imperfecciones</li>
  <li><strong>Carbón activado de bambú</strong>: absorbe toxinas e impurezas del poro sin irritar la piel</li>
  <li><strong>Proceso cold process</strong>: preserva todos los nutrientes activos del aceite de coco, manteca de karité y aceite de oliva</li>
  <li><strong>Sin sulfatos, parabenos ni SLS</strong>: formulado para pieles reactivas y atópicas</li>
  <li><strong>Aroma natural de menta y eucalipto</strong>: aceites esenciales puros para un efecto refrescante y tonificante</li>
  <li><strong>Peso neto</strong>: 100 g — duración aproximada de 3-4 semanas con uso diario</li>
</ul>
<p>Apto para cara y cuerpo. Vegano, cruelty-free, sin microplásticos. Empaque en papel kraft 100% reciclado.</p>',
        9.99,
        'Cuidado Natural',
        100,
        '/storage/products/seed-emerald-soap-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-soap-1.jpg'),
    ('/storage/products/seed-emerald-cream-1.jpg'),
    ('/storage/products/seed-emerald-soap-1.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Crema Corporal Nutritiva de Manteca de Karité 200ml',
        '<p>La crema corporal que transforma la piel más seca en una piel suave y luminosa. Con <strong>manteca de karité sin refinar al 40%</strong> y aceite de argán marroquí para una hidratación que dura todo el día.</p>
<ul>
  <li><strong>Manteca de karité cruda al 40%</strong>: concentración premium que repara grietas, nutela y suaviza la piel más seca</li>
  <li><strong>Aceite de argán de primera presión</strong>: rico en ácidos grasos omega y vitamina E para elasticidad y brillo</li>
  <li><strong>Vitamina E y C</strong>: antioxidantes que previenen el envejecimiento prematuro y unifican el tono</li>
  <li><strong>Aroma a vainilla y coco</strong>: fragancia delicada de aceites esenciales — sin artificiales</li>
  <li><strong>Textura rich & fast-absorb</strong>: se absorbe sin dejar residuo graso — aplicable antes de vestirse</li>
  <li><strong>Para todo el cuerpo</strong>: especialmente recomendada para codos, talones, manos y zonas secas</li>
</ul>
<p>Vegana, cruelty-free. Sin parabenos, sin silicones. 200 ml. Tarro de vidrio reutilizable con tapa de aluminio.</p>',
        19.99,
        'Cuidado Natural',
        65,
        '/storage/products/seed-emerald-cream-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-cream-1.jpg'),
    ('/storage/products/seed-emerald-soap-1.jpg'),
    ('/storage/products/seed-emerald-veggies-2.jpg')
) AS imgs(img);

-- ── Infusiones ────────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Matcha Ceremonial Premium Japonés 100g',
        '<p>El matcha de más alta calidad: cultivado en <strong>Uji, Kyoto</strong> bajo técnica tradicional de sombreado (tana), molido en piedra de granito para obtener un polvo ultrafino de un verde vibrante e intenso.</p>
<ul>
  <li><strong>Grado ceremonial</strong>: primer ciclo de cosecha (Ichibancha, mayo) — el más suave, dulce y rico en L-teanina</li>
  <li><strong>L-Teanina + cafeína natural</strong>: energía sostenida sin nerviosismo ni crash — concentración y calma al mismo tiempo</li>
  <li><strong>EGCG (catequinas)</strong>: antioxidante 137× más potente que el té verde convencional</li>
  <li><strong>Color verde jade intenso</strong>: indicador de clorofila alta y frescura del polvo</li>
  <li><strong>Sabor umami complejo</strong>: notas de hierba fresca, almendra y dulzor natural — sin amargura</li>
  <li><strong>100 g en lata hermética</strong>: con válvula desoxigenante para conservar la frescura hasta 18 meses</li>
</ul>
<p>Preparación recomendada: 1 g de polvo + 70 ml de agua a 70°C. Ideal para latte de matcha, smoothies y repostería premium.</p>',
        24.99,
        'Infusiones',
        40,
        '/storage/products/seed-emerald-matcha-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-matcha-1.jpg'),
    ('/storage/products/seed-emerald-matcha-2.jpg'),
    ('/storage/products/seed-emerald-honey-1.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Miel Pura de Abejas Artesanal con Panal 500g',
        '<p>Una miel cruda excepcional, directamente del colmenar a tu mesa. <strong>Sin filtrar, sin pasteurizar, sin mezclas</strong> — conserva todas las enzimas, propóleos y antioxidantes que la hacen única.</p>
<ul>
  <li><strong>Miel cruda sin procesar</strong>: nunca calentada por encima de los 40°C — preserva diastasas, invertasas y glucosa oxidasa</li>
  <li><strong>Con trozos de panal</strong>: cera de abejas natural rica en ésteres y fitoquímicos beneficiosos para la salud</li>
  <li><strong>Origen certificado</strong>: colmenas en zonas de montaña, libres de pesticidas y contaminación</li>
  <li><strong>Polifenoles y flavonoides</strong>: propiedades antimicrobianas, antiinflamatorias y antioxidantes comprobadas</li>
  <li><strong>Cristalización natural</strong>: señal de pureza — calienta levemente al baño María para volver líquida sin perder propiedades</li>
  <li><strong>Índice glucémico bajo</strong>: comparado con el azúcar refinada gracias a la fructosa natural presente</li>
</ul>
<p>Tarro de vidrio hermético 500 g. Ideal para endulzar infusiones, yogur, tostadas y como sustituto del azúcar en repostería saludable.</p>',
        14.99,
        'Infusiones',
        90,
        '/storage/products/seed-emerald-honey-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-emerald-honey-1.jpg'),
    ('/storage/products/seed-emerald-honey-2.jpg'),
    ('/storage/products/seed-emerald-matcha-2.jpg')
) AS imgs(img);
