-- =============================================================================
-- Eonsclover — Demo Seed: Carbón (tienda5)
-- =============================================================================
-- Run AFTER seed.sql. Settings snapshotted from live tenant (tenant_tienda5).
-- NOTE: Runs in the tenant schema context (search_path already set).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. NEWSLETTER SUBSCRIBERS TABLE (safety for older installs)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT NOT NULL UNIQUE,
    subscribed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT 'home'
);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON newsletter_subscribers (email);

-- ---------------------------------------------------------------------------
-- 1. APP SETTINGS  (snapshotted from tenant_tienda5)
-- ---------------------------------------------------------------------------
UPDATE app_settings SET value = '#0ea5e9'
WHERE id = 'accentColor';
UPDATE app_settings SET value = '#8396aa'
WHERE id = 'backgroundColor';
UPDATE app_settings SET value = '{"useDefault":false,"categories":[{"id":"todos","name":"Todos","icon":"🔧","slug":"todos","image":""},{"id":"herramientas","name":"Herramientas","icon":"🔧","slug":"Herramientas","image":""},{"id":"automotriz","name":"Automotriz","icon":"🚗","slug":"Automotriz","image":""},{"id":"equipamiento","name":"Equipamiento","icon":"🎒","slug":"Equipamiento","image":""},{"id":"electronica","name":"Electrónica","icon":"🔋","slug":"Electrónica","image":""},{"id":"seguridad","name":"Seguridad","icon":"🦺","slug":"Seguridad","image":""}],"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"","cardBackground":"","cardBorderColor":"","cardShadow":"","hoverBackground":"","hoverBorderColor":"","hoverShadow":"","hoverTitleColor":"","activeBackground":"","activeBorderColor":"","activeShadow":"","titleColor":"","activeTitleColor":"","titleSize":"","titleWeight":"","titleTransform":"","titleLetterSpacing":"","iconSize":""}}'
WHERE id = 'categoryFiltersConfig';
UPDATE app_settings SET value = '#374151'
WHERE id = 'chatbotColor';
UPDATE app_settings SET value = 'false'
WHERE id = 'chatbotEnabled';
UPDATE app_settings SET value = '¡Hola! 👋 Soy el asistente de Eonsclover. ¿En qué puedo ayudarte?'
WHERE id = 'chatbotGreeting';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmModel';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmProvider';
UPDATE app_settings SET value = '50'
WHERE id = 'chatbotMaxMessages';
UPDATE app_settings SET value = '500'
WHERE id = 'chatbotMaxTokens';
UPDATE app_settings SET value = 'helpful'
WHERE id = 'chatbotPersonality';
UPDATE app_settings SET value = 'Escribe tu mensaje...'
WHERE id = 'chatbotPlaceholder';
UPDATE app_settings SET value = '0.7'
WHERE id = 'chatbotTemperature';
UPDATE app_settings SET value = 'normal'
WHERE id = 'chatbotVerbosity';
UPDATE app_settings SET value = ''
WHERE id = 'contactAddress';
UPDATE app_settings SET value = 'Eonsclover'
WHERE id = 'contactCompany';
UPDATE app_settings SET value = ''
WHERE id = 'contactEmail';
UPDATE app_settings SET value = 'Lunes a Viernes: 9:00 AM - 6:00 PM'
WHERE id = 'contactHours';
UPDATE app_settings SET value = ''
WHERE id = 'contactPhone';
UPDATE app_settings SET value = '¿Tienes preguntas? Estamos aquí para ayudarte'
WHERE id = 'contactSubtitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactSupportLine';
UPDATE app_settings SET value = 'Contáctanos'
WHERE id = 'contactTitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactWhatsapp';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailInvoiceAutoSend';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailOrderConfirmation';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailPasswordReset';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyGuestCheckout';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyRegistration';
UPDATE app_settings SET value = 'system-ui, sans-serif'
WHERE id = 'fontFamily';
UPDATE app_settings SET value = '{"brandMessage":"Tu tienda de confianza para todos los dispositivos electrónicos y accesorios.","quickLinksTitle":"Enlaces Rápidos","quickLinks":[{"label":"Inicio","href":"/","enabled":true},{"label":"Productos","href":"/tienda","enabled":true},{"label":"Ofertas","href":"/tienda?promo=1","enabled":true},{"label":"Sobre Nosotros","href":"/contacto","enabled":true}],"supportTitle":"Atención al Cliente","supportLinks":[{"label":"Contáctanos","href":"/contacto","enabled":true},{"label":"Devoluciones","href":"/contacto","enabled":true},{"label":"Preguntas Frecuentes","href":"/contacto","enabled":true},{"label":"Estado del Pedido","href":"/orders","enabled":true}],"socialTitle":"Síguenos","socialLinks":[{"icon":"📘","href":"","enabled":true},{"icon":"📱","href":"","enabled":true},{"icon":"📷","href":"","enabled":true},{"icon":"🐦","href":"","enabled":true}],"copyrightText":"© 2026 Eonsclover. Todos los derechos reservados."}'
WHERE id = 'footerConfig';
UPDATE app_settings SET value = '50000'
WHERE id = 'freeShippingThreshold';
UPDATE app_settings SET value = '#1f2937'
WHERE id = 'headerBgColor';
UPDATE app_settings SET value = '#f9fafb'
WHERE id = 'headerButtonColor';
UPDATE app_settings SET value = '#1f2937'
WHERE id = 'headerButtonTextColor';
UPDATE app_settings SET value = '#f9fafb'
WHERE id = 'headerTextColor';
UPDATE app_settings SET value = '100'
WHERE id = 'headerTransparency';
UPDATE app_settings SET value = '/storage/products/seed-carbon-banner.jpg'
WHERE id = 'heroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'heroBannerOpacity';
UPDATE app_settings SET value = 'right'
WHERE id = 'heroBannerPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'heroBannerPositionY';
UPDATE app_settings SET value = '260'
WHERE id = 'heroBannerSize';
UPDATE app_settings SET value = 'Equipamiento profesional, accesorios automotrices y herramientas de alta calidad para quienes no aceptan productos que fallen cuando más se necesitan.'
WHERE id = 'heroDescription';
UPDATE app_settings SET value = '1.05'
WHERE id = 'heroDescriptionSize';
UPDATE app_settings SET value = '420'
WHERE id = 'heroHeight';
UPDATE app_settings SET value = '/storage/products/seed-carbon-hero-bg.jpg'
WHERE id = 'heroImage';
UPDATE app_settings SET value = '50'
WHERE id = 'heroImageBgX';
UPDATE app_settings SET value = '50'
WHERE id = 'heroImageBgY';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageBgZoom';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageWidth';
UPDATE app_settings SET value = '0.55'
WHERE id = 'heroOverlayOpacity';
UPDATE app_settings SET value = 'left'
WHERE id = 'heroPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'heroPositionY';
UPDATE app_settings SET value = 'Ver Herramientas'
WHERE id = 'heroPrimaryBtn';
UPDATE app_settings SET value = 'Accesorios Auto'
WHERE id = 'heroSecondaryBtn';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'heroTextColor';
UPDATE app_settings SET value = '0'
WHERE id = 'heroTextPaddingX';
UPDATE app_settings SET value = '0'
WHERE id = 'heroTextPaddingY';
UPDATE app_settings SET value = 'Herramientas para los que Hacen'
WHERE id = 'heroTitle';
UPDATE app_settings SET value = '2.1'
WHERE id = 'heroTitleSize';
UPDATE app_settings SET value = '{}'
WHERE id = 'invoicePdfConfig';
UPDATE app_settings SET value = '{"enabled":false,"route":"/landing","pageTitle":"Ofertas Especiales","templateId":"modern-minimal","globalStyles":{"fontFamily":"inherit","darkColor":"var(--secondary-color)","lightColor":"var(--background-color)","accentColor":"var(--primary-color)","accentHoverColor":"var(--primary-hover)","textColor":"var(--text-color)","textLightColor":"var(--text-color)","headingColor":"var(--text-color)","maxWidth":1200,"sectionPadding":80,"sectionPaddingMobile":48},"sections":[{"id":"hero","type":"hero","enabled":true,"data":{"layout":"text-left","title":"La Mejor Tecnología a Tu Alcance","subtitle":"Descubre productos premium con la mejor calidad y precios incomparables.","ctaText":"Comprar Ahora","ctaLink":"/","image":"","badgeText":"","badgeColor":"var(--primary-color)"},"styles":{"bgColor":"var(--secondary-color)","bgGradient":"","bgImage":"","bgOverlayOpacity":0.5,"textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","minHeight":500}},{"id":"valueProposition","type":"valueProposition","enabled":true,"data":{"label":"Nuestras Ventajas","title":"¿Por qué elegirnos?","description":"Ofrecemos la mejor experiencia de compra con beneficios exclusivos para ti.","points":[{"icon":"🚚","iconImage":"","title":"Envío Gratis","description":""},{"icon":"🛡️","iconImage":"","title":"Garantía Total","description":""},{"icon":"💰","iconImage":"","title":"Mejor Precio","description":""},{"icon":"🔒","iconImage":"","title":"Pago Seguro","description":""}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","iconBgColor":"var(--background-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.08)"}},{"id":"productHighlight","type":"productHighlight","enabled":true,"data":{"layout":"image-left","label":"Propuesta Única","title":"Producto Destacado","description":"Descripción del producto y sus beneficios clave para el cliente. Enfócate en el valor que aporta.","ctaText":"Ver Más","ctaLink":"/","image":""},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"trustBanner","type":"trustBanner","enabled":true,"data":{"title":"Valorado por nuestros clientes","subtitle":"Miles de clientes satisfechos confían en nosotros cada día."},"styles":{"bgColor":"var(--primary-color)","textColor":"var(--background-color)"}},{"id":"featuredProduct","type":"featuredProduct","enabled":true,"data":{"label":"El mejor producto","productName":"Audífonos Inalámbricos Pro","productId":null,"image":"","specs":[{"key":"Tipo","value":"Inalámbrico"},{"key":"Batería","value":"40 horas"},{"key":"Cancelación de ruido","value":"Sí"},{"key":"Peso","value":"250g"}],"description":"Sonido premium con cancelación de ruido activa. La mejor experiencia auditiva.","originalPrice":158,"salePrice":118.99,"badgeText":"OFERTA","ctaText":"Comprar Ahora","ctaLink":"/"},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","priceSaleColor":"var(--primary-color)","priceOriginalColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","specsDotColor":"var(--secondary-color)"}},{"id":"howItWorks","type":"howItWorks","enabled":true,"data":{"title":"¿Cómo Funciona?","steps":[{"number":"1","title":"Explora","description":"Navega nuestra colección de productos tecnológicos."},{"number":"2","title":"Selecciona","description":"Elige tu producto favorito y agrégalo al carrito."},{"number":"3","title":"Recibe","description":"Completa tu compra y recíbelo en la puerta de tu casa."}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","stepNumberBg":"var(--primary-color)","stepNumberColor":"var(--background-color)","stepCardBg":"var(--background-color)","stepCardBorder":"var(--secondary-color)"}},{"id":"productShowcase","type":"productShowcase","enabled":true,"data":{"title":"Productos Destacados","subtitle":"Descubre nuestras mejores ofertas en tecnología.","products":[{"productId":null,"name":"Laptop Gaming","description":"Alto rendimiento para gaming profesional.","category":"Laptops","image":"","features":["Procesador ultra rápido","Gráficos inmersivos","Batería duradera"],"originalPrice":1189,"salePrice":899,"badgeText":"30% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Audífonos Wireless","description":"Sonido cristalino con cancelación de ruido.","category":"Audio","image":"","features":["Cancelación de ruido","Batería extendida","Audio superior"],"originalPrice":199,"salePrice":59.7,"badgeText":"70% OFF","badgeColor":"var(--accent-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Teclado Mecánico","description":"Teclas responsivas para gaming y productividad.","category":"Periféricos","image":"","features":["RGB backlight","Switches resistentes","Diseño ergonómico"],"originalPrice":129,"salePrice":89,"badgeText":"31% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Monitor 4K","description":"Visuales ultra HD con colores vívidos.","category":"Monitores","image":"","features":["Alta tasa de refresco","Amplia gama de colores","Soporte ajustable"],"originalPrice":499,"salePrice":399.2,"badgeText":"20% OFF","badgeColor":"var(--secondary-color)","ctaText":"Ver Producto","ctaLink":"/"}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 4px 12px rgba(0,0,0,0.1)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"testimonials","type":"testimonials","enabled":true,"data":{"title":"Lo que dicen nuestros clientes","subtitle":"Opiniones reales de compradores verificados.","items":[{"quote":"Excelente calidad y servicio rápido. Totalmente recomendado.","author":"María García","avatar":"","rating":5},{"quote":"Los mejores precios del mercado y atención personalizada.","author":"Carlos Rodríguez","avatar":"","rating":5},{"quote":"Compra segura y envío rápido. Volveré a comprar sin duda.","author":"Ana Martínez","avatar":"","rating":4},{"quote":"El mejor sonido que he escuchado. Producto increíble.","author":"Pedro López","avatar":"","rating":5}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.06)","quoteColor":"var(--text-color)","authorColor":"var(--text-color)","starColor":"var(--accent-color)"}},{"id":"leadCapture","type":"leadCapture","enabled":false,"data":{"title":"¡Obtén tu descuento exclusivo!","description":"Completa el formulario y recibe códigos de descuento directamente en tu email.","aboutText":"Somos un equipo apasionado que ofrece tecnología de primera calidad a precios imbatibles.","fields":["name","email"],"submitText":"Enviar","successMessage":"¡Gracias! Revisa tu correo para tu código de descuento."},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","inputBgColor":"var(--background-color)","inputBorderColor":"var(--secondary-color)","submitBgColor":"var(--primary-color)","submitTextColor":"var(--background-color)"}},{"id":"finalCta","type":"finalCta","enabled":true,"data":{"title":"¿Qué esperas?","subtitle":"Aprovecha nuestras ofertas antes de que se agoten.","ctaText":"Ir a la Tienda","ctaLink":"/"},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}}]}'
WHERE id = 'landingPageConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'maintenanceMode';
UPDATE app_settings SET value = '{"mapEnabled":true,"shippingCalcEnabled":true,"storeLocation":{"lat":18.462673,"lng":-69.936051},"shippingZones":[{"maxDistance":5,"price":100,"label":"Zona 1"},{"maxDistance":10,"price":150,"label":"Zona 2"},{"maxDistance":20,"price":200,"label":"Zona 3"},{"maxDistance":50,"price":350,"label":"Zona 4"},{"maxDistance":9999,"price":600,"label":"Zona 5"}]}'
WHERE id = 'mapConfig';
UPDATE app_settings SET value = '{"showHomeLink":true,"showStoreLink":true}'
WHERE id = 'navigationConfig';
UPDATE app_settings SET value = '{"enabled":false,"title":"Únete a Nuestra Newsletter","text":"Recibe las últimas noticias sobre tecnología y ofertas exclusivas directamente en tu correo.","placeholder":"Tu correo electrónico","buttonText":"Suscribirse"}'
WHERE id = 'newsletterConfig';
UPDATE app_settings SET value = '{"cash":{"enabled":true,"name":"Pago Contra Entrega","description":"Paga en efectivo cuando recibas tu pedido","icon":"💵","order":1},"transfer":{"enabled":true,"name":"Transferencia Bancaria","description":"Transferencia o depósito bancario","icon":"🏦","order":2,"bankName":"","bankHolder":"","bankAccount":"","transferNote":""},"stripe":{"enabled":true,"name":"Tarjeta de Crédito/Débito","description":"Visa, MasterCard, American Express","icon":"💳","order":3,"testMode":true},"paypal":{"enabled":false,"name":"PayPal","description":"Paga con tu cuenta PayPal","icon":"🅿️","order":4}}'
WHERE id = 'paymentMethodsConfig';
UPDATE app_settings SET value = '#374151'
WHERE id = 'primaryColor';
UPDATE app_settings SET value = '{"useDefault":true,"layout":{"orientation":"vertical","columnsMobile":2,"columnsTablet":3,"columnsDesktop":4,"columnsWide":5},"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"","borderWidth":"","borderStyle":"","borderColor":"","background":"","shadow":"","titleColor":"","titleSize":"","titleWeight":"","priceColor":"","priceSize":"","priceWeight":"","descriptionColor":"","descriptionSize":"","categoryColor":"","categorySize":"","buttonBg":"","buttonText":"","buttonRadius":"","buttonBorder":"","buttonShadow":""},"currency":"DOP"}'
WHERE id = 'productCardConfig';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'productDetailHeroBannerOpacity';
UPDATE app_settings SET value = 'right'
WHERE id = 'productDetailHeroBannerPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'productDetailHeroBannerPositionY';
UPDATE app_settings SET value = '120'
WHERE id = 'productDetailHeroBannerSize';
UPDATE app_settings SET value = '200'
WHERE id = 'productDetailHeroHeight';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroImage';
UPDATE app_settings SET value = '40'
WHERE id = 'productDetailHeroOverlayOpacity';
UPDATE app_settings SET value = 'false'
WHERE id = 'productDetailUseHomeHero';
UPDATE app_settings SET value = 'Ver Oferta'
WHERE id = 'promoButtonText';
UPDATE app_settings SET value = '/storage/products/seed-carbon-promo.jpg'
WHERE id = 'promoImage';
UPDATE app_settings SET value = '6'
WHERE id = 'promoProductId';
UPDATE app_settings SET value = '🔧 ¡Oferta del Mes! Lleva cualquier juego de herramientas y obtén un 25% de descuento en todos los accesorios automotrices seleccionados.'
WHERE id = 'promoText';
UPDATE app_settings SET value = '¡Oferta Especial del Mes!'
WHERE id = 'promoTitle';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'searchBarConfig';
UPDATE app_settings SET value = '#4b5563'
WHERE id = 'secondaryColor';
UPDATE app_settings SET value = '{}'
WHERE id = 'seoConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'shippingSlipEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'showPromotionBanner';
UPDATE app_settings SET value = '🛍️'
WHERE id = 'siteIcon';
UPDATE app_settings SET value = ''
WHERE id = 'siteLogo';
UPDATE app_settings SET value = '40'
WHERE id = 'siteLogoSize';
UPDATE app_settings SET value = ''
WHERE id = 'siteNameImage';
UPDATE app_settings SET value = '120'
WHERE id = 'siteNameImageSize';
UPDATE app_settings SET value = ''
WHERE id = 'storeAddress';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'storeModuleConfig';
UPDATE app_settings SET value = ''
WHERE id = 'storePhone';
UPDATE app_settings SET value = '#111827'
WHERE id = 'textColor';
UPDATE app_settings SET value = '{"enabled":true,"sectionTitle":"¿Por Qué Elegirnos?","items":[{"icon":"🚚","title":"Envío Gratis","text":"En todos tus pedidos superiores a $50"},{"icon":"⚡","title":"Garantía Extendida","text":"12 meses adicionales en todos nuestros productos"},{"icon":"🔒","title":"Pago Seguro","text":"Todas las transacciones son 100% seguras"}]}'
WHERE id = 'whyChooseUsConfig';

-- ---------------------------------------------------------------------------
-- 2. DEMO PRODUCTS
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- 2. SAMPLE PRODUCTS — automotive & tools store
-- ---------------------------------------------------------------------------

-- ── Herramientas ─────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Juego de Herramientas Profesional 108 Piezas',
        '<p>El juego de herramientas más completo para el taller doméstico o profesional. <strong>108 piezas de cromo vanadio</strong> organizadas en un maletín de aluminio con espuma moldeada — todo en su lugar, siempre.</p>
<ul>
  <li><strong>Acero cromo vanadio (Cr-V)</strong>: aleación de alta resistencia a la torsión, duración y acabado espejo resistente a la corrosión</li>
  <li><strong>Juego completo</strong>: 22 vasos métricos y SAE (1/4" y 3/8"), 2 trinquetes, 8 destornilladores, 10 llaves combinadas, 5 llaves allen, 3 alicates y mucho más</li>
  <li><strong>Trinquete de 72 dientes</strong>: arco de giro mínimo de 5° — trabaja en espacios reducidos sin comprometer el par</li>
  <li><strong>Maletín de aluminio</strong>: cierres metálicos con bisagras reforzadas y espuma EVA moldeada por CNC para cada pieza</li>
  <li><strong>Certificado DIN/ISO</strong>: cumple con estándares europeos de calidad para uso profesional</li>
  <li><strong>Garantía de por vida</strong>: cambio inmediato de cualquier pieza defectuosa sin preguntas</li>
</ul>
<p>Peso total del set: 8.2 kg. Dimensiones del maletín: 45 × 35 × 15 cm. El regalo perfecto para el mecánico, el carpintero o el manitas de la familia.</p>',
        89.99,
        'Herramientas',
        25,
        '/storage/products/seed-carbon-tools-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-tools-1.jpg'),
    ('/storage/products/seed-carbon-tools-2.jpg'),
    ('/storage/products/seed-carbon-tools-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Multímetro Digital Profesional AutoRango',
        '<p>El multímetro que usan los profesionales. Con <strong>rango automático, pantalla LCD con retroiluminación</strong> y categoría de seguridad CAT III 600V, mide con precisión en entornos industriales y domésticos.</p>
<ul>
  <li><strong>AutoRango inteligente</strong>: selecciona automáticamente el rango óptimo — sin ajuste manual, lecturas más rápidas</li>
  <li><strong>Mediciones completas</strong>: tensión AC/DC (600V), corriente AC/DC (10A), resistencia (60MΩ), continuidad, diodo, temperatura y frecuencia</li>
  <li><strong>Pantalla LCD 4000 conteos</strong>: retroiluminación azul, retención de datos (HOLD), lectura relativa (REL)</li>
  <li><strong>CAT III 600V</strong>: categoría de seguridad para paneles eléctricos, armarios de distribución y equipos industriales</li>
  <li><strong>Sonda de temperatura tipo K incluida</strong>: mide desde -40°C hasta 400°C para HVAC y electrónica</li>
  <li><strong>Carcasa de doble inyección</strong>: protección contra caídas desde 1 m, resistente a polvo y líquidos</li>
</ul>
<p>Incluye puntas de prueba profesionales con aislamiento 1000V, bolsa de transporte y 2 baterías AAA. Certificado CE y RoHS.</p>',
        34.99,
        'Herramientas',
        40,
        '/storage/products/seed-carbon-multimeter-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-multimeter-1.jpg'),
    ('/storage/products/seed-carbon-multimeter-2.jpg'),
    ('/storage/products/seed-carbon-tools-1.jpg')
) AS imgs(img);

-- ── Automotriz ────────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Compresor de Aire Portátil 12V 150 PSI',
        '<p>Infla tus neumáticos en minutos desde cualquier lugar. El <strong>compresor digital de 12V con pantalla LCD</strong> que se conecta al encendedor del auto y alcanza 150 PSI — suficiente para coches, SUVs, pickups y bicicletas.</p>
<ul>
  <li><strong>Presión máxima 150 PSI</strong>: infla un neumático P215/65R16 desde 0 hasta 35 PSI en menos de 6 minutos</li>
  <li><strong>Pantalla digital LCD</strong>: lectura en PSI, BAR, KPA o kg/cm² — selección de unidades con un botón</li>
  <li><strong>Apagado automático</strong>: programa la presión objetivo y se detiene solo — sin sobreinflado nunca</li>
  <li><strong>Cable de 3 metros</strong>: longitud suficiente para llegar a los 4 neumáticos desde el habitáculo</li>
  <li><strong>Linterna LED integrada</strong>: útil para emergencias nocturnas o en garajes con poca luz</li>
  <li><strong>Boquillas de repuesto</strong>: incluye adaptadores para válvulas Presta, pelotas deportivas y colchones</li>
</ul>
<p>Peso: 0.85 kg. Cable de alimentación con fusible de protección. Bolsa de transporte incluida. Temperatura de trabajo: -20°C a +60°C.</p>',
        49.99,
        'Automotriz',
        35,
        '/storage/products/seed-carbon-compressor-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-compressor-1.jpg'),
    ('/storage/products/seed-carbon-banner.jpg'),
    ('/storage/products/seed-carbon-tools-2.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Dashcam 4K Ultra HD con GPS y Visión Nocturna',
        '<p>Protege tu auto y tus derechos en cualquier situación. La <strong>cámara de tablero 4K con SONY STARVIS</strong> graba cada detalle de la carretera — incluso de noche — con GPS integrado para rastrear velocidad y ruta.</p>
<ul>
  <li><strong>Grabación 4K 30fps</strong>: sensor SONY STARVIS de gran tamaño con apertura f/1.8 — imagen nítida de día y de noche</li>
  <li><strong>Ángulo de 170°</strong>: campo de visión ultraancho que cubre todos los carriles y los laterales del vehículo</li>
  <li><strong>GPS integrado</strong>: registra velocidad, coordenadas y ruta en cada clip de vídeo para máxima evidencia</li>
  <li><strong>WDR (Wide Dynamic Range)</strong>: equilibra automáticamente la exposición en túneles, sol directo y faros nocturnos</li>
  <li><strong>Modo Parking</strong>: monitorea el vehículo aparcado y graba solo si detecta movimiento o impacto</li>
  <li><strong>Instalación sin cables visibles</strong>: cable ultra-delgado que se oculta por la junta del parabrisas</li>
</ul>
<p>Compatible con tarjetas microSD hasta 256 GB (no incluida). App móvil para revisión en tiempo real. Soporte de ventosa 3M incluido. Garantía 2 años.</p>',
        79.99,
        'Automotriz',
        20,
        '/storage/products/seed-carbon-dashcam-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-dashcam-1.jpg'),
    ('/storage/products/seed-carbon-dashcam-2.jpg'),
    ('/storage/products/seed-carbon-dashcam-3.jpg')
) AS imgs(img);

-- ── Equipamiento ─────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Linterna Táctica LED 1000 Lúmenes Recargable',
        '<p>La linterna que no te deja sin luz cuando más la necesitas. <strong>1000 lúmenes de potencia real</strong>, cuerpo en aluminio aeronáutico T6 y batería recargable por USB-C para tener siempre luz máxima disponible.</p>
<ul>
  <li><strong>LED CREE XHP50</strong>: 1000 lúmenes reales (verificado) con alcance de hasta 300 metros en modo máximo</li>
  <li><strong>5 modos de iluminación</strong>: Turbo (1000 lm) / Alto (500 lm) / Medio (200 lm) / Bajo (50 lm) / Stroboscópico de emergencia</li>
  <li><strong>Batería 5000 mAh integrada</strong>: hasta 8 horas en modo medio — carga por USB-C en 3 horas</li>
  <li><strong>Cuerpo de aluminio T6</strong>: grado aeronáutico, resistente a impactos de 2 metros y clasificación IP68 (sumergible)</li>
  <li><strong>Zoom telescópico</strong>: ajusta el haz de flood a spot para iluminar cerca o a distancia</li>
  <li><strong>Memoria de modo</strong>: recuerda el último modo usado al encender para no deslumbrarte de madrugada</li>
</ul>
<p>Peso: 185 g con batería. Cable de carga USB-C y correa de mano incluidos. Certificado IP68. Temperatura de trabajo: -30°C a +50°C.</p>',
        24.99,
        'Equipamiento',
        60,
        '/storage/products/seed-carbon-flashlight-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-flashlight-1.jpg'),
    ('/storage/products/seed-carbon-tools-2.jpg'),
    ('/storage/products/seed-carbon-tools-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Navaja Multiusos 18 Funciones Acero Inoxidable',
        '<p>La herramienta de bolsillo que resuelve cualquier situación. Con <strong>18 funciones en acero inoxidable 440C</strong> y mango de aluminio anodizado, es compacta, robusta y siempre lista.</p>
<ul>
  <li><strong>18 funciones integradas</strong>: hoja, sierra, destornillador plano y Phillips, abrelatas, sacacorchos, lima, tijeras, alicate y más</li>
  <li><strong>Acero inoxidable 440C</strong>: alta dureza (58 HRC), resistencia a la corrosión y filo duradero que no se oxida</li>
  <li><strong>Mango de aluminio anodizado</strong>: ligero, robusto y con grip de textura diamond para agarre seguro mojado</li>
  <li><strong>Cierre de seguridad</strong>: bloqueo de hoja con mecanismo de seguridad que previene cierres accidentales</li>
  <li><strong>Apertura con una mano</strong>: hoja principal con muesca para apertura rápida de pulgar</li>
  <li><strong>Clip de cinturón reversible</strong>: discreto, resistente y extraíble — llévala siempre contigo</li>
</ul>
<p>Peso: 120 g. Dimensiones plegada: 11 × 3.5 cm. Funda de nylon MOLLE incluida. Certificado CPSC. No apta para menores de 18 años.</p>',
        19.99,
        'Equipamiento',
        75,
        '/storage/products/seed-carbon-knife-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-knife-1.jpg'),
    ('/storage/products/seed-carbon-tools-1.jpg'),
    ('/storage/products/seed-carbon-flashlight-1.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Mochila Táctica Impermeable 40L MOLLE',
        '<p>La mochila diseñada para los que no se quedan en casa. Con <strong>40 litros de capacidad y sistema MOLLE</strong>, es la compañera ideal para senderismo, camping, viajes o la ciudad.</p>
<ul>
  <li><strong>Nylon 900D ripstop</strong>: tela de alta densidad con tratamiento DWR — repele agua, soporta rasgados y abrasión</li>
  <li><strong>Sistema MOLLE en exterior</strong>: filas de webbing para añadir bolsillos, fundas y accesorios modulares</li>
  <li><strong>40 L de capacidad organizada</strong>: compartimento principal, funda hidratación 3L, bolsillo laptop 17", 4 bolsillos exteriores</li>
  <li><strong>Soporte lumbar acolchado</strong>: panel trasero con canales de ventilación y correas de pecho y cadera ajustables</li>
  <li><strong>Acceso lateral</strong>: abre desde los lados para sacar objetos del fondo sin vaciar la mochila</li>
  <li><strong>Asas de carga reforzadas</strong>: costuras dobles en puntos de estrés máximo para cargas de hasta 30 kg</li>
</ul>
<p>Peso vacío: 1.4 kg. Incluye cubierta impermeable de lluvia. Compatible con sistemas de hidratación de 2-3L. Colores: Negro táctico, Verde militar, Gris urbano.</p>',
        59.99,
        'Equipamiento',
        30,
        '/storage/products/seed-carbon-backpack-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-backpack-1.jpg'),
    ('/storage/products/seed-carbon-backpack-2.jpg'),
    ('/storage/products/seed-carbon-promo.jpg')
) AS imgs(img);

-- ── Electrónica ───────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Cargador Solar Portátil + Power Bank 20000mAh',
        '<p>Energía ilimitada donde no llega el enchufe. El <strong>panel solar de alta eficiencia (28%) combinado con batería de 20000 mAh</strong> mantiene todos tus dispositivos cargados en camping, senderismo o emergencias.</p>
<ul>
  <li><strong>Panel solar SunPower 28% eficiencia</strong>: los más eficientes del mercado — genera 18W en condiciones óptimas de sol directo</li>
  <li><strong>Batería de 20000 mAh integrada</strong>: almacena la energía solar para usar de noche o bajo techo — hasta 5 cargas completas de smartphone</li>
  <li><strong>Carga rápida USB-C 18W PD</strong>: carga un iPhone de 0 a 100% en 1.5 horas desde la batería interna</li>
  <li><strong>3 puertos de salida</strong>: USB-C PD 18W + 2× USB-A 12W — carga hasta 3 dispositivos simultáneamente</li>
  <li><strong>Resistente IP67</strong>: protegido contra polvo y sumergible hasta 1 metro durante 30 minutos</li>
  <li><strong>Mosquetones de enganche</strong>: cuelga del exterior de la mochila mientras caminas para cargar en movimiento</li>
</ul>
<p>Peso: 680 g. Dimensiones desplegado: 39 × 18 cm. Carcasa de PET reciclado. Incluye cables USB-C y USB-A. Garantía 18 meses.</p>',
        44.99,
        'Electrónica',
        35,
        '/storage/products/seed-carbon-solar-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-solar-1.jpg'),
    ('/storage/products/seed-carbon-solar-2.jpg'),
    ('/storage/products/seed-carbon-backpack-1.jpg')
) AS imgs(img);

-- ── Seguridad ─────────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Guantes de Trabajo Anticorte Nivel 5 Talla L',
        '<p>Los guantes que protegen de verdad. Con <strong>recubrimiento de nitrilo en palma y nivel de corte A5 (EN388)</strong>, estos guantes defienden tus manos contra objetos afilados, abrasión y punciones sin sacrificar la destreza.</p>
<ul>
  <li><strong>Nivel de corte A5 (ANSI/ISEA 105)</strong>: el estándar más alto para trabajo con vidrio, chapa, cuchillas y metales</li>
  <li><strong>Fibra HPPE + acero inoxidable</strong>: núcleo de alta resistencia que no se comprime ni se deforma bajo presión de corte</li>
  <li><strong>Recubrimiento de nitrilo espumado</strong>: agarre excepcional en superficies húmedas, aceitosas y secas</li>
  <li><strong>Palma reforzada zona pulgar</strong>: la zona de mayor fricción lleva doble capa de nitrilo para mayor durabilidad</li>
  <li><strong>Dorso transpirable</strong>: tejido de punto fino que permite ventilación y flexibilidad total de los dedos</li>
  <li><strong>Talla L ajustada</strong>: disponible en S, M, L, XL y XXL — consulta tabla de tallas en imágenes del producto</li>
</ul>
<p>Lavables a máquina a 40°C. Certificado EN388 4X43F, EN ISO 21420. Peso por par: 68 g. Apto para automoción, logística, construcción y jardinería.</p>',
        14.99,
        'Seguridad',
        90,
        '/storage/products/seed-carbon-gloves-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-carbon-gloves-1.jpg'),
    ('/storage/products/seed-carbon-gloves-2.jpg'),
    ('/storage/products/seed-carbon-tools-1.jpg')
) AS imgs(img);
