-- =============================================================================
-- Eonsclover — Demo Seed: Tech Azul (tienda1)
-- =============================================================================
-- Run AFTER seed.sql. Settings snapshotted from live tenant (tenant_tienda1).
-- NOTE: Runs in the tenant schema context (search_path already set).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. NEWSLETTER SUBSCRIBERS TABLE (safety for older installs)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT NOT NULL UNIQUE,
    subscribed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source          TEXT NOT NULL DEFAULT 'home'
);
CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON newsletter_subscribers (email);

-- ---------------------------------------------------------------------------
-- 1. APP SETTINGS  (snapshotted from tenant_tienda1)
-- ---------------------------------------------------------------------------
UPDATE app_settings SET value = '#ec4899'
WHERE id = 'accentColor';
UPDATE app_settings SET value = '#947cab'
WHERE id = 'backgroundColor';
UPDATE app_settings SET value = '{"useDefault":false,"categories":[{"id":"todos","name":"Todos","icon":"🏪","slug":"todos","image":""},{"id":"smartphones","name":"Smartphones","icon":"📱","slug":"Smartphones","image":""},{"id":"luces-led","name":"Luces LED","icon":"🔅","slug":"Luces LED","image":""},{"id":"casa-inteligente","name":"Casa Inteligente","icon":"🏠","slug":"Casa Inteligente","image":""},{"id":"auriculares","name":"Auriculares","icon":"🎧","slug":"Auriculares","image":""},{"id":"accesorios","name":"Accesorios","icon":"🔌","slug":"Accesorios","image":""},{"id":"estilo-vida","name":"Estilo de Vida","icon":"✨","slug":"Estilo de Vida","image":""}],"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"","cardBackground":"","cardBorderColor":"","cardShadow":"","hoverBackground":"","hoverBorderColor":"","hoverShadow":"","hoverTitleColor":"","activeBackground":"","activeBorderColor":"","activeShadow":"","titleColor":"","activeTitleColor":"","titleSize":"","titleWeight":"","titleTransform":"","titleLetterSpacing":"","iconSize":"48"},"filterStyle":"cards","filterImageSize":5}'
WHERE id = 'categoryFiltersConfig';
UPDATE app_settings SET value = '#2563eb'
WHERE id = 'chatbotColor';
UPDATE app_settings SET value = 'false'
WHERE id = 'chatbotEnabled';
UPDATE app_settings SET value = '¡Hola! 👋 Soy el asistente de Eonsclover. ¿En qué puedo ayudarte?'
WHERE id = 'chatbotGreeting';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmModel';
UPDATE app_settings SET value = ''
WHERE id = 'chatbotLlmProvider';
UPDATE app_settings SET value = '50'
WHERE id = 'chatbotMaxMessages';
UPDATE app_settings SET value = '500'
WHERE id = 'chatbotMaxTokens';
UPDATE app_settings SET value = 'helpful'
WHERE id = 'chatbotPersonality';
UPDATE app_settings SET value = 'Escribe tu mensaje...'
WHERE id = 'chatbotPlaceholder';
UPDATE app_settings SET value = '0.7'
WHERE id = 'chatbotTemperature';
UPDATE app_settings SET value = 'normal'
WHERE id = 'chatbotVerbosity';
UPDATE app_settings SET value = ''
WHERE id = 'contactAddress';
UPDATE app_settings SET value = 'Eonsclover'
WHERE id = 'contactCompany';
UPDATE app_settings SET value = ''
WHERE id = 'contactEmail';
UPDATE app_settings SET value = 'Lunes a Viernes: 9:00 AM - 6:00 PM'
WHERE id = 'contactHours';
UPDATE app_settings SET value = ''
WHERE id = 'contactPhone';
UPDATE app_settings SET value = '¿Tienes preguntas? Estamos aquí para ayudarte'
WHERE id = 'contactSubtitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactSupportLine';
UPDATE app_settings SET value = 'Contáctanos'
WHERE id = 'contactTitle';
UPDATE app_settings SET value = ''
WHERE id = 'contactWhatsapp';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailInvoiceAutoSend';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailOrderConfirmation';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailPasswordReset';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyGuestCheckout';
UPDATE app_settings SET value = 'true'
WHERE id = 'emailVerifyRegistration';
UPDATE app_settings SET value = 'system-ui, sans-serif'
WHERE id = 'fontFamily';
UPDATE app_settings SET value = '{"brandMessage":"Tu tienda de confianza para todos los dispositivos electrónicos y accesorios.","quickLinksTitle":"Enlaces Rápidos","quickLinks":[{"label":"Inicio","href":"/","enabled":true},{"label":"Productos","href":"/tienda","enabled":true},{"label":"Ofertas","href":"/tienda?promo=1","enabled":true},{"label":"Sobre Nosotros","href":"/contacto","enabled":true}],"supportTitle":"Atención al Cliente","supportLinks":[{"label":"Contáctanos","href":"/contacto","enabled":true},{"label":"Devoluciones","href":"/contacto","enabled":true},{"label":"Preguntas Frecuentes","href":"/contacto","enabled":true},{"label":"Estado del Pedido","href":"/orders","enabled":true}],"socialTitle":"Síguenos","socialLinks":[{"icon":"📘","href":"","enabled":true},{"icon":"📱","href":"","enabled":true},{"icon":"📷","href":"","enabled":true},{"icon":"🐦","href":"","enabled":true}],"copyrightText":"© 2026 Eonsclover. Todos los derechos reservados."}'
WHERE id = 'footerConfig';
UPDATE app_settings SET value = '50000'
WHERE id = 'freeShippingThreshold';
UPDATE app_settings SET value = '#7c3aed'
WHERE id = 'headerBgColor';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'headerButtonColor';
UPDATE app_settings SET value = '#7c3aed'
WHERE id = 'headerButtonTextColor';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'headerTextColor';
UPDATE app_settings SET value = '100'
WHERE id = 'headerTransparency';
UPDATE app_settings SET value = '/storage/products/seedoverhero.jpg'
WHERE id = 'heroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'heroBannerOpacity';
UPDATE app_settings SET value = '70'
WHERE id = 'heroBannerPositionX';
UPDATE app_settings SET value = '10'
WHERE id = 'heroBannerPositionY';
UPDATE app_settings SET value = '600'
WHERE id = 'heroBannerSize';
UPDATE app_settings SET value = 'Descubre nuestra selección de smartphones, auriculares y accesorios con las mejores ofertas del mercado.'
WHERE id = 'heroDescription';
UPDATE app_settings SET value = '1.05'
WHERE id = 'heroDescriptionSize';
UPDATE app_settings SET value = '410'
WHERE id = 'heroHeight';
UPDATE app_settings SET value = '/storage/products/wp9314387-4k-technology-desktop-wallpapers-1780200813672.jpg'
WHERE id = 'heroImage';
UPDATE app_settings SET value = '130'
WHERE id = 'heroImageBgZoom';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageWidth';
UPDATE app_settings SET value = '100'
WHERE id = 'heroImageZoom';
UPDATE app_settings SET value = '0.05'
WHERE id = 'heroOverlayOpacity';
UPDATE app_settings SET value = 'left'
WHERE id = 'heroPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'heroPositionY';
UPDATE app_settings SET value = 'Comprar ahora'
WHERE id = 'heroPrimaryBtn';
UPDATE app_settings SET value = 'Ver Ofertas'
WHERE id = 'heroSecondaryBtn';
UPDATE app_settings SET value = '#ffffff'
WHERE id = 'heroTextColor';
UPDATE app_settings SET value = '30'
WHERE id = 'heroTextPaddingX';
UPDATE app_settings SET value = '10'
WHERE id = 'heroTextPaddingY';
UPDATE app_settings SET value = 'La Mejor Tecnología a Tu Alcance'
WHERE id = 'heroTitle';
UPDATE app_settings SET value = '2.1'
WHERE id = 'heroTitleSize';
UPDATE app_settings SET value = '{}'
WHERE id = 'invoicePdfConfig';
UPDATE app_settings SET value = '{"enabled":false,"route":"/landing","pageTitle":"Ofertas Especiales","templateId":"modern-minimal","globalStyles":{"fontFamily":"inherit","darkColor":"var(--secondary-color)","lightColor":"var(--background-color)","accentColor":"var(--primary-color)","accentHoverColor":"var(--primary-hover)","textColor":"var(--text-color)","textLightColor":"var(--text-color)","headingColor":"var(--text-color)","maxWidth":1200,"sectionPadding":80,"sectionPaddingMobile":48},"sections":[{"id":"hero","type":"hero","enabled":true,"data":{"layout":"text-left","title":"La Mejor Tecnología a Tu Alcance","subtitle":"Descubre productos premium con la mejor calidad y precios incomparables.","ctaText":"Comprar Ahora","ctaLink":"/","image":"","badgeText":"","badgeColor":"var(--primary-color)"},"styles":{"bgColor":"var(--secondary-color)","bgGradient":"","bgImage":"","bgOverlayOpacity":0.5,"textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","minHeight":500}},{"id":"valueProposition","type":"valueProposition","enabled":true,"data":{"label":"Nuestras Ventajas","title":"¿Por qué elegirnos?","description":"Ofrecemos la mejor experiencia de compra con beneficios exclusivos para ti.","points":[{"icon":"🚚","iconImage":"","title":"Envío Gratis","description":""},{"icon":"🛡️","iconImage":"","title":"Garantía Total","description":""},{"icon":"💰","iconImage":"","title":"Mejor Precio","description":""},{"icon":"🔒","iconImage":"","title":"Pago Seguro","description":""}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","iconBgColor":"var(--background-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.08)"}},{"id":"productHighlight","type":"productHighlight","enabled":true,"data":{"layout":"image-left","label":"Propuesta Única","title":"Producto Destacado","description":"Descripción del producto y sus beneficios clave para el cliente. Enfócate en el valor que aporta.","ctaText":"Ver Más","ctaLink":"/","image":""},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"trustBanner","type":"trustBanner","enabled":true,"data":{"title":"Valorado por nuestros clientes","subtitle":"Miles de clientes satisfechos confían en nosotros cada día."},"styles":{"bgColor":"var(--primary-color)","textColor":"var(--background-color)"}},{"id":"featuredProduct","type":"featuredProduct","enabled":true,"data":{"label":"El mejor producto","productName":"Audífonos Inalámbricos Pro","productId":null,"image":"","specs":[{"key":"Tipo","value":"Inalámbrico"},{"key":"Batería","value":"40 horas"},{"key":"Cancelación de ruido","value":"Sí"},{"key":"Peso","value":"250g"}],"description":"Sonido premium con cancelación de ruido activa. La mejor experiencia auditiva.","originalPrice":158,"salePrice":118.99,"badgeText":"OFERTA","ctaText":"Comprar Ahora","ctaLink":"/"},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","priceSaleColor":"var(--primary-color)","priceOriginalColor":"var(--text-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)","specsDotColor":"var(--secondary-color)"}},{"id":"howItWorks","type":"howItWorks","enabled":true,"data":{"title":"¿Cómo Funciona?","steps":[{"number":"1","title":"Explora","description":"Navega nuestra colección de productos tecnológicos."},{"number":"2","title":"Selecciona","description":"Elige tu producto favorito y agrégalo al carrito."},{"number":"3","title":"Recibe","description":"Completa tu compra y recíbelo en la puerta de tu casa."}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","stepNumberBg":"var(--primary-color)","stepNumberColor":"var(--background-color)","stepCardBg":"var(--background-color)","stepCardBorder":"var(--secondary-color)"}},{"id":"productShowcase","type":"productShowcase","enabled":true,"data":{"title":"Productos Destacados","subtitle":"Descubre nuestras mejores ofertas en tecnología.","products":[{"productId":null,"name":"Laptop Gaming","description":"Alto rendimiento para gaming profesional.","category":"Laptops","image":"","features":["Procesador ultra rápido","Gráficos inmersivos","Batería duradera"],"originalPrice":1189,"salePrice":899,"badgeText":"30% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Audífonos Wireless","description":"Sonido cristalino con cancelación de ruido.","category":"Audio","image":"","features":["Cancelación de ruido","Batería extendida","Audio superior"],"originalPrice":199,"salePrice":59.7,"badgeText":"70% OFF","badgeColor":"var(--accent-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Teclado Mecánico","description":"Teclas responsivas para gaming y productividad.","category":"Periféricos","image":"","features":["RGB backlight","Switches resistentes","Diseño ergonómico"],"originalPrice":129,"salePrice":89,"badgeText":"31% OFF","badgeColor":"var(--primary-color)","ctaText":"Ver Producto","ctaLink":"/"},{"productId":null,"name":"Monitor 4K","description":"Visuales ultra HD con colores vívidos.","category":"Monitores","image":"","features":["Alta tasa de refresco","Amplia gama de colores","Soporte ajustable"],"originalPrice":499,"salePrice":399.2,"badgeText":"20% OFF","badgeColor":"var(--secondary-color)","ctaText":"Ver Producto","ctaLink":"/"}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 4px 12px rgba(0,0,0,0.1)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}},{"id":"testimonials","type":"testimonials","enabled":true,"data":{"title":"Lo que dicen nuestros clientes","subtitle":"Opiniones reales de compradores verificados.","items":[{"quote":"Excelente calidad y servicio rápido. Totalmente recomendado.","author":"María García","avatar":"","rating":5},{"quote":"Los mejores precios del mercado y atención personalizada.","author":"Carlos Rodríguez","avatar":"","rating":5},{"quote":"Compra segura y envío rápido. Volveré a comprar sin duda.","author":"Ana Martínez","avatar":"","rating":4},{"quote":"El mejor sonido que he escuchado. Producto increíble.","author":"Pedro López","avatar":"","rating":5}]},"styles":{"bgColor":"var(--background-color)","textColor":"var(--text-color)","cardBgColor":"var(--background-color)","cardBorderColor":"var(--secondary-color)","cardShadow":"0 2px 8px rgba(0,0,0,0.06)","quoteColor":"var(--text-color)","authorColor":"var(--text-color)","starColor":"var(--accent-color)"}},{"id":"leadCapture","type":"leadCapture","enabled":false,"data":{"title":"¡Obtén tu descuento exclusivo!","description":"Completa el formulario y recibe códigos de descuento directamente en tu email.","aboutText":"Somos un equipo apasionado que ofrece tecnología de primera calidad a precios imbatibles.","fields":["name","email"],"submitText":"Enviar","successMessage":"¡Gracias! Revisa tu correo para tu código de descuento."},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","inputBgColor":"var(--background-color)","inputBorderColor":"var(--secondary-color)","submitBgColor":"var(--primary-color)","submitTextColor":"var(--background-color)"}},{"id":"finalCta","type":"finalCta","enabled":true,"data":{"title":"¿Qué esperas?","subtitle":"Aprovecha nuestras ofertas antes de que se agoten.","ctaText":"Ir a la Tienda","ctaLink":"/"},"styles":{"bgColor":"var(--secondary-color)","textColor":"var(--background-color)","ctaBgColor":"var(--primary-color)","ctaTextColor":"var(--background-color)"}}]}'
WHERE id = 'landingPageConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'maintenanceMode';
UPDATE app_settings SET value = '{"mapEnabled":true,"shippingCalcEnabled":true,"storeLocation":{"lat":18.462673,"lng":-69.936051},"shippingZones":[{"maxDistance":5,"price":100,"label":"Zona 1"},{"maxDistance":10,"price":150,"label":"Zona 2"},{"maxDistance":20,"price":200,"label":"Zona 3"},{"maxDistance":50,"price":350,"label":"Zona 4"},{"maxDistance":9999,"price":600,"label":"Zona 5"}]}'
WHERE id = 'mapConfig';
UPDATE app_settings SET value = '{"showHomeLink":true,"showStoreLink":true}'
WHERE id = 'navigationConfig';
UPDATE app_settings SET value = '{"enabled":true,"title":"Únete a Nuestra Newsletter","text":"Recibe las últimas noticias sobre tecnología y ofertas exclusivas directamente en tu correo.","placeholder":"Tu correo electrónico","buttonText":"Suscribirse"}'
WHERE id = 'newsletterConfig';
UPDATE app_settings SET value = '{"cash":{"enabled":true,"name":"Pago Contra Entrega","description":"Paga en efectivo cuando recibas tu pedido","icon":"💵","order":1},"transfer":{"enabled":true,"name":"Transferencia Bancaria","description":"Transferencia o depósito bancario","icon":"🏦","order":2,"bankName":"","bankHolder":"","bankAccount":"","transferNote":""},"stripe":{"enabled":true,"name":"Tarjeta de Crédito/Débito","description":"Visa, MasterCard, American Express","icon":"💳","order":3,"testMode":true},"paypal":{"enabled":false,"name":"PayPal","description":"Paga con tu cuenta PayPal","icon":"🅿️","order":4}}'
WHERE id = 'paymentMethodsConfig';
UPDATE app_settings SET value = '#7c3aed'
WHERE id = 'primaryColor';
UPDATE app_settings SET value = '{"useDefault":false,"layout":{"orientation":"vertical","columnsMobile":2,"columnsTablet":3,"columnsDesktop":4,"columnsWide":5},"styles":{"cardWidth":"","cardHeight":"","cardPadding":"","cardRadius":"8px","borderWidth":"1px","borderStyle":"solid","borderColor":"#dde3ea","background":"#ffffff","shadow":"0 2px 8px rgba(0,0,0,0.07)","titleColor":"","titleSize":"","titleWeight":"","priceColor":"","priceSize":"","priceWeight":"","descriptionColor":"","descriptionSize":"","categoryColor":"","categorySize":"","buttonBg":"","buttonText":"","buttonRadius":"","buttonBorder":"","buttonShadow":""},"currency":"EUR","fineLayoutActive":true}'
WHERE id = 'productCardConfig';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroBannerImage';
UPDATE app_settings SET value = '100'
WHERE id = 'productDetailHeroBannerOpacity';
UPDATE app_settings SET value = 'right'
WHERE id = 'productDetailHeroBannerPositionX';
UPDATE app_settings SET value = 'center'
WHERE id = 'productDetailHeroBannerPositionY';
UPDATE app_settings SET value = '120'
WHERE id = 'productDetailHeroBannerSize';
UPDATE app_settings SET value = '400'
WHERE id = 'productDetailHeroHeight';
UPDATE app_settings SET value = ''
WHERE id = 'productDetailHeroImage';
UPDATE app_settings SET value = '0.05'
WHERE id = 'productDetailHeroOverlayOpacity';
UPDATE app_settings SET value = 'true'
WHERE id = 'productDetailUseHomeHero';
UPDATE app_settings SET value = 'Ver Oferta'
WHERE id = 'promoButtonText';
UPDATE app_settings SET value = '/storage/products/seed-airpods-1.jpg'
WHERE id = 'promoImage';
UPDATE app_settings SET value = '4'
WHERE id = 'promoProductId';
UPDATE app_settings SET value = '🔥 ¡Oferta del Mes! Obtén un 20% de descuento en todos nuestros accesorios al comprar cualquier smartphone.'
WHERE id = 'promoText';
UPDATE app_settings SET value = '¡Oferta Especial del Mes!'
WHERE id = 'promoTitle';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'searchBarConfig';
UPDATE app_settings SET value = '#6d28d9'
WHERE id = 'secondaryColor';
UPDATE app_settings SET value = '{}'
WHERE id = 'seoConfig';
UPDATE app_settings SET value = 'false'
WHERE id = 'shippingSlipEnabled';
UPDATE app_settings SET value = 'true'
WHERE id = 'showPromotionBanner';
UPDATE app_settings SET value = ''
WHERE id = 'siteIcon';
UPDATE app_settings SET value = ''
WHERE id = 'siteLogo';
UPDATE app_settings SET value = '42'
WHERE id = 'siteLogoSize';
UPDATE app_settings SET value = ''
WHERE id = 'siteNameImage';
UPDATE app_settings SET value = '60'
WHERE id = 'siteNameImageSize';
UPDATE app_settings SET value = ''
WHERE id = 'storeAddress';
UPDATE app_settings SET value = '{"enabled":true}'
WHERE id = 'storeModuleConfig';
UPDATE app_settings SET value = ''
WHERE id = 'storePhone';
UPDATE app_settings SET value = '#1e293b'
WHERE id = 'textColor';
UPDATE app_settings SET value = '{"enabled":true,"sectionTitle":"¿Por Qué Elegirnos?","items":[{"icon":"🚚","title":"Envío Gratis","text":"En todos tus pedidos superiores a $50"},{"icon":"⚡","title":"Garantía Extendida","text":"12 meses adicionales en todos nuestros productos"},{"icon":"🔒","title":"Pago Seguro","text":"Todas las transacciones son 100% seguras"}]}'
WHERE id = 'whyChooseUsConfig';

-- ---------------------------------------------------------------------------
-- 2. DEMO PRODUCTS
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------
-- 2. SAMPLE PRODUCTS — tech store with rich descriptions & gallery images
-- ---------------------------------------------------------------------------

-- ── Smartphones ─────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'iPhone 15 Pro Max 256GB',
        '<p>El smartphone más avanzado de Apple. Fabricado en <strong>titanio de grado aeroespacial</strong>, el iPhone 15 Pro Max redefine lo que es posible en la palma de tu mano.</p>
<ul>
  <li><strong>Chip A17 Pro</strong>: el procesador móvil más potente del mercado con acelerador de IA neuronal</li>
  <li><strong>Cámara Pro de 48 MP</strong>: lente tetraprismática con zoom óptico 5× y vídeo ProRes 4K 120fps</li>
  <li><strong>Pantalla Super Retina XDR</strong>: 6.7" con ProMotion 120 Hz, brillo máximo de 2000 nits</li>
  <li><strong>USB-C USB 3</strong>: transferencias hasta 20 Gb/s y compatibilidad con monitores externos</li>
  <li><strong>Action Button</strong>: botón personalizable para acceso rápido a tus funciones favoritas</li>
  <li><strong>Batería</strong>: hasta 29 horas de reproducción continua de vídeo</li>
</ul>
<p>Disponible en Titanio Negro, Titanio Blanco, Titanio Azul y Titanio Natural. Incluye cargador USB-C y cable USB-C.</p>',
        1199.00,
        'Smartphones',
        15,
        '/storage/products/seed-iphone-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-iphone-1.jpg'),
    ('/storage/products/seed-iphone-2.jpg'),
    ('/storage/products/seed-iphone-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Samsung Galaxy S24 Ultra',
        '<p>La máxima expresión de Android con <strong>inteligencia artificial Galaxy AI</strong> integrada en cada función. Diseñado para quienes no aceptan compromisos.</p>
<ul>
  <li><strong>Snapdragon 8 Gen 3</strong>: rendimiento de élite con IA nativa para productividad y creatividad</li>
  <li><strong>S Pen integrado</strong>: escribe, esboza y controla con precisión milimétrica</li>
  <li><strong>Cámara cuádruple 200 MP</strong>: zoom espacial 100× y vídeo 8K para capturas cinematográficas</li>
  <li><strong>Pantalla Dynamic AMOLED 2X</strong>: 6.8" con 120 Hz adaptativo y brillo de 2600 nits</li>
  <li><strong>Galaxy AI</strong>: traducción en vivo, resumen de notas, Circle to Search y edición generativa</li>
  <li><strong>Batería 5000 mAh</strong>: carga rápida de 45 W y carga inalámbrica de 15 W</li>
</ul>
<p>Incluye S Pen integrado. Disponible en Titanium Black, Titanium Gray, Titanium Violet y Titanium Yellow.</p>',
        999.00,
        'Smartphones',
        20,
        '/storage/products/seed-samsung-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-samsung-1.jpg'),
    ('/storage/products/seed-samsung-2.jpg'),
    ('/storage/products/seed-samsung-3.jpg')
) AS imgs(img);

-- ── Auriculares ──────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Sony WH-1000XM5',
        '<p>Reconocidos mundialmente como los <strong>mejores auriculares inalámbricos con cancelación de ruido</strong>, los WH-1000XM5 elevan la experiencia auditiva a un nivel sin precedentes.</p>
<ul>
  <li><strong>Cancelación de ruido líder</strong>: 8 micrófonos y 2 procesadores (QN1e + HD Noise Cancelling) eliminan el ruido de fondo con precisión</li>
  <li><strong>Audio Hi-Res Wireless</strong>: compatible con LDAC para streaming a 990 kbps — casi sin pérdidas</li>
  <li><strong>30 horas de batería</strong>: con cancelación activa; solo 3 minutos de carga = 3 horas de reproducción</li>
  <li><strong>Multiconexión Bluetooth</strong>: conecta y cambia entre 2 dispositivos simultáneamente</li>
  <li><strong>Speak-to-Chat</strong>: pausa automática la música en cuanto comienzas a hablar</li>
  <li><strong>Nuevo diseño rediseñado</strong>: más ligero, almohadillas más suaves, arco más flexible para uso prolongado</li>
</ul>
<p>Incluye funda de transporte, cable USB-C y cable de audio de 3.5 mm. Disponible en Negro y Plata.</p>',
        349.99,
        'Auriculares',
        30,
        '/storage/products/seed-sony-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-sony-1.jpg'),
    ('/storage/products/seed-sony-2.jpg'),
    ('/storage/products/seed-sony-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'AirPods Pro (2da Generación)',
        '<p>Los <strong>AirPods Pro de segunda generación</strong> ofrecen cancelación activa de ruido mejorada, audio espacial personalizado y hasta 30 horas de batería total.</p>
<ul>
  <li><strong>Chip H2</strong>: cancelación de ruido activa 2× más potente que la primera generación</li>
  <li><strong>Audio Espacial Personalizado</strong>: se adapta a la anatomía única de tus orejas para un sonido inmersivo</li>
  <li><strong>Modo Transparencia Adaptativo</strong>: escucha el ambiente que te rodea con naturalidad</li>
  <li><strong>Batería</strong>: hasta 6 horas por carga y 30 horas totales con la funda MagSafe</li>
  <li><strong>Funda MagSafe</strong>: carga inalámbrica, compatible con Apple Watch y Qi; altavoz integrado para localización</li>
  <li><strong>Resistencia al agua</strong>: IPX4 en auriculares y funda para protección frente a salpicaduras</li>
</ul>
<p>Incluye funda de carga MagSafe con USB-C y tres tallas de almohadillas (XS/S/M/L). Compatible con iPhone, iPad, Mac y Apple Watch.</p>',
        249.99,
        'Auriculares',
        25,
        '/storage/products/seed-airpods-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-airpods-1.jpg'),
    ('/storage/products/seed-airpods-2.jpg'),
    ('/storage/products/seed-airpods-3.jpg')
) AS imgs(img);

-- ── Luces LED ────────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Tira LED RGB 5 Metros',
        '<p>Transforma cualquier espacio con <strong>16 millones de colores</strong> y efectos de iluminación dinámicos. Compatible con voz y aplicación móvil para un control total.</p>
<ul>
  <li><strong>5 metros de LEDs de alta densidad</strong>: 60 LEDs/metro para una iluminación uniforme y brillante</li>
  <li><strong>16 millones de colores RGB</strong>: personaliza cada tono y elige entre más de 20 modos de efecto</li>
  <li><strong>App Smart Life / Tuya</strong>: controla desde tu smartphone con programación horaria y escenas</li>
  <li><strong>Compatibilidad con voz</strong>: funciona con Amazon Alexa, Google Assistant y Siri Shortcuts</li>
  <li><strong>Adhesivo 3M resistente</strong>: se adhiere en superficies planas y se corta cada 3 LEDs a medida</li>
  <li><strong>Bajo consumo</strong>: solo 24 W para los 5 metros completos</li>
</ul>
<p>Ideal para dormitorios, escritorios, TV backlight y decoración de fiestas. Incluye controlador WiFi y fuente de alimentación.</p>',
        19.99,
        'Luces LED',
        100,
        '/storage/products/seed-led-strip-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-led-strip-1.jpg'),
    ('/storage/products/seed-led-strip-2.jpg'),
    ('/storage/products/seed-led-strip-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Foco LED Inteligente WiFi 10W',
        '<p>Iluminación inteligente <strong>E27 de 10 W</strong> con control por voz y aplicación. Ahorra hasta un 80% de energía frente a focos incandescentes tradicionales.</p>
<ul>
  <li><strong>Ajuste de temperatura</strong>: de 2700 K (cálido) a 6500 K (frío) para cada momento del día</li>
  <li><strong>Brillo regulable</strong>: 0–100% para crear el ambiente perfecto</li>
  <li><strong>Control por voz</strong>: compatible con Alexa, Google Assistant y Apple HomeKit</li>
  <li><strong>App Smart Life</strong>: programación horaria, escenas de luz y control remoto desde cualquier lugar</li>
  <li><strong>Equivalente a 75 W</strong>: 806 lúmenes con solo 10 W de consumo real</li>
  <li><strong>Vida útil de 25 000 horas</strong>: más de 22 años a 3 horas/día</li>
</ul>
<p>Base E27 estándar. Compatible con la mayoría de lámparas domésticas. No requiere hub — conexión WiFi directa 2.4 GHz.</p>',
        15.99,
        'Luces LED',
        80,
        '/storage/products/seed-bulb-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-bulb-1.jpg'),
    ('/storage/products/seed-led-strip-3.jpg')
) AS imgs(img);

-- ── Casa Inteligente ─────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Amazon Echo Dot (5ta Generación)',
        '<p>El altavoz inteligente más popular del mundo en su versión más avanzada. Con <strong>Alexa integrada</strong>, controla tu hogar, reproduce música y responde cualquier pregunta.</p>
<ul>
  <li><strong>Sonido mejorado</strong>: altavoz de 1.73" rediseñado para bajos más profundos y sonido más nítido</li>
  <li><strong>Sensor de temperatura ambiental</strong>: monitoriza la temperatura de la habitación desde la app Alexa</li>
  <li><strong>Modo Tapón Earplugs</strong>: detecta sonidos como alarmas de humo y te notifica en el móvil</li>
  <li><strong>Centro de control del hogar inteligente</strong>: Zigbee, Matter y Thread integrados — sin hub adicional</li>
  <li><strong>Privacidad garantizada</strong>: botón físico para desactivar el micrófono cuando lo desees</li>
  <li><strong>Conecta con todo</strong>: más de 100 000 dispositivos compatibles de cientos de marcas</li>
</ul>
<p>Disponible en Gris Carbón, Azul Glaciar y Blanco Nube. Incluye adaptador de corriente.</p>',
        49.99,
        'Casa Inteligente',
        40,
        '/storage/products/seed-echo-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-echo-1.jpg'),
    ('/storage/products/seed-echo-2.jpg'),
    ('/storage/products/seed-echo-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Enchufe Inteligente WiFi 16A',
        '<p>Convierte cualquier electrodoméstico en <strong>inteligente en segundos</strong>. Monitoriza el consumo eléctrico en tiempo real y programa el encendido y apagado desde cualquier lugar.</p>
<ul>
  <li><strong>Control remoto</strong>: enciende y apaga cualquier dispositivo desde tu smartphone, estés donde estés</li>
  <li><strong>Monitor de consumo</strong>: mide vatios, amperios y kWh en tiempo real para optimizar tu factura</li>
  <li><strong>16 A / 3680 W</strong>: apto para electrodomésticos de alta potencia (lavadora, aire acondicionado)</li>
  <li><strong>Programación horaria</strong>: temporizadores diarios y semanales con múltiples horarios</li>
  <li><strong>Compatible con voz</strong>: funciona con Alexa, Google Assistant y Apple HomeKit</li>
  <li><strong>Diseño compacto</strong>: no bloquea el enchufe adyacente; LED de estado visible</li>
</ul>
<p>Compatible con enchufes estándar europeos (tipo F/Schuko). Conexión WiFi 2.4 GHz. No requiere hub.</p>',
        15.99,
        'Casa Inteligente',
        60,
        '/storage/products/seed-plug-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-plug-1.jpg'),
    ('/storage/products/seed-led-strip-1.jpg')
) AS imgs(img);

-- ── Accesorios ───────────────────────────────────────────────────────────────

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Razer DeathAdder V3',
        '<p>El ratón gaming <strong>más vendido de la historia</strong>, ahora en su versión más ligera y precisa. Diseñado para competir al máximo nivel con un perfil ergonómico insuperable.</p>
<ul>
  <li><strong>Sensor Focus Pro 30K</strong>: hasta 30 000 DPI con seguimiento óptico de precisión absoluta en cualquier superficie</li>
  <li><strong>Switches ópticos Razer Gen-3</strong>: 90 millones de clics de vida útil con activación instantánea sin rebote</li>
  <li><strong>Diseño ergonómico optimizado</strong>: 59 g ultraligero con forma estudiada para grip palmar y clawgrip</li>
  <li><strong>HyperPolling 8000 Hz</strong>: 8 veces más respuesta que los ratones estándar de 1000 Hz</li>
  <li><strong>Cable SpeedFlex</strong>: ultraflexible, simula la sensación de un ratón inalámbrico</li>
  <li><strong>Razer Synapse 3</strong>: personalización avanzada de botones, sensibilidad y macros</li>
</ul>
<p>Con cable USB-A. Compatible con Windows, macOS y Linux. Dimensiones: 128.1 × 68.0 × 44.0 mm. Peso: 59 g.</p>',
        89.99,
        'Accesorios',
        25,
        '/storage/products/seed-mouse-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-mouse-1.jpg'),
    ('/storage/products/seed-mouse-2.jpg'),
    ('/storage/products/seed-mouse-3.jpg')
) AS imgs(img);

WITH p AS (
    INSERT INTO products (name, description, price, category, stock, image)
    VALUES (
        'Cable USB-C 100W 2 Metros',
        '<p>Cable USB-C de alta velocidad con soporte para <strong>carga rápida 100 W</strong> y transferencia de datos USB 3.2 Gen 2. Construido para durar con trenzado de nylon reforzado.</p>
<ul>
  <li><strong>Carga rápida 100 W</strong>: carga tu laptop, tablet y smartphone a máxima velocidad con cualquier cargador USB-C PD</li>
  <li><strong>USB 3.2 Gen 2</strong>: transferencia de datos a 10 Gbps — 10× más rápido que USB 2.0</li>
  <li><strong>Compatibilidad universal</strong>: MacBook, iPad Pro, Galaxy S24, iPhone 15, Nintendo Switch y cualquier dispositivo USB-C</li>
  <li><strong>Nylon trenzado reforzado</strong>: resistencia a más de 25 000 dobleces sin dañar el cable</li>
  <li><strong>Cabezales de aluminio</strong>: conectores robustos con diseño reversible para no equivocarte al conectar</li>
  <li><strong>2 metros de longitud</strong>: perfecta para escritorio, cama o escritorio en cualquier posición</li>
</ul>
<p>Incluye 1 cable USB-C a USB-C de 2 m. Certificado USB-IF. Compatible con Thunderbolt 3/4 para vídeo 4K (requiere cable Thunderbolt nativo para velocidades máximas).</p>',
        12.99,
        'Accesorios',
        150,
        '/storage/products/seed-cable-1.jpg'
    )
    RETURNING id
)
INSERT INTO product_images (product_id, image_path)
SELECT id, img FROM p, (VALUES
    ('/storage/products/seed-cable-1.jpg'),
    ('/storage/products/seed-hero-bg.jpg')
) AS imgs(img);
