#!/bin/bash
# =============================================================================
# TechStore — Docker deploy on fresh Ubuntu 22.04 ARM64
# =============================================================================
# Run this on the VM after SSH-ing in:
#   curl -fsSL https://raw.githubusercontent.com/treborg88/TechStore/main/scripts/docker-deploy.sh | bash
#
# Or manually:
#   ssh -i ~/.ssh/oci_test ubuntu@<VM_IP>
#   bash scripts/docker-deploy.sh
#
# What it does:
#   1. Install Docker Engine + Compose plugin
#   2. Clone the repo
#   3. Generate a random JWT_SECRET
#   4. Start the full stack (PostgreSQL + backend + frontend + nginx)
#   5. Print access URLs
# =============================================================================

set -euo pipefail

APP_DIR="$HOME/TechStore"
REPO_URL="https://github.com/treborg88/TechStore.git"
BRANCH="main"

echo "╔══════════════════════════════════════════════════════╗"
echo "║   TechStore — Docker Full Stack Deploy (ARM64)       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── 1. Install Docker ────────────────────────────────────
echo "📦 Installing Docker Engine..."
if ! command -v docker &>/dev/null; then
  # Official Docker install script (supports ARM64)
  curl -fsSL https://get.docker.com | sudo sh
  # Add current user to docker group (avoids sudo)
  sudo usermod -aG docker "$USER"
  echo "✅ Docker installed: $(docker --version)"
else
  echo "✅ Docker already installed: $(docker --version)"
fi

# Ensure docker compose plugin is available
if ! docker compose version &>/dev/null; then
  echo "📦 Installing Docker Compose plugin..."
  sudo apt-get update -y
  sudo apt-get install -y docker-compose-plugin
fi
echo "✅ Docker Compose: $(docker compose version)"

# ── 1b. Open firewall ports (Ubuntu iptables) ───────────
echo ""
echo "🔥 Configuring firewall (iptables)..."
# Insert HTTP/HTTPS rules before the REJECT rule (position 5 and 6)
# Check if rule already exists to avoid duplicates
if ! sudo iptables -C INPUT -p tcp --dport 80 -j ACCEPT 2>/dev/null; then
  sudo iptables -I INPUT 5 -p tcp --dport 80 -j ACCEPT -m comment --comment "TechStore HTTP"
  echo "   ✅ Port 80 (HTTP) opened"
else
  echo "   ✅ Port 80 already open"
fi
if ! sudo iptables -C INPUT -p tcp --dport 443 -j ACCEPT 2>/dev/null; then
  sudo iptables -I INPUT 6 -p tcp --dport 443 -j ACCEPT -m comment --comment "TechStore HTTPS"
  echo "   ✅ Port 443 (HTTPS) opened"
else
  echo "   ✅ Port 443 already open"
fi
# Persist rules across reboots
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent >/dev/null 2>&1 || true
sudo netfilter-persistent save >/dev/null 2>&1 || true
echo "   ✅ Firewall rules saved"

# ── 2. Clone repository ──────────────────────────────────
echo ""
echo "📂 Cloning repository..."
if [ -d "$APP_DIR" ]; then
  echo "   Directory exists, pulling latest..."
  cd "$APP_DIR"
  git pull origin "$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
  cd "$APP_DIR"
fi

# ── 3. Create .env file ──────────────────────────────────
echo ""
echo "🔐 Generating environment config..."

# Generate random JWT_SECRET (64 chars)
JWT_SECRET=$(openssl rand -hex 32)

# Create backend .env with Docker defaults
cat > backend/.env <<EOF
# Auto-generated by docker-deploy.sh — $(date -Iseconds)
JWT_SECRET=${JWT_SECRET}
PORT=5001
NODE_ENV=production

# Database: Docker PostgreSQL (configured by docker-compose.yml)
DATABASE_URL=postgresql://techstore:techstore@database:5432/techstore
EOF

echo "✅ backend/.env created (JWT_SECRET generated)"

# ── 4. Build & start containers ──────────────────────────
echo ""
echo "🐳 Building and starting containers..."
echo "   (This may take 3-5 minutes on first run)"
echo ""

# Use newgrp to get docker group in current session, or sudo
if groups | grep -q docker; then
  docker compose up --build -d
else
  sudo docker compose up --build -d
fi

# ── 5. Wait for health checks ────────────────────────────
echo ""
echo "⏳ Waiting for services to start..."
sleep 10

# Check container status
echo ""
echo "📊 Container status:"
if groups | grep -q docker; then
  docker compose ps
else
  sudo docker compose ps
fi

# ── 6. Print access info ─────────────────────────────────
PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "UNKNOWN")

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   🎉 Deploy complete!                                ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║   App:      http://${PUBLIC_IP}                      ║"
echo "║   API:      http://${PUBLIC_IP}/api/products         ║"
echo "║   Setup:    http://${PUBLIC_IP}  (first visit)       ║"
echo "║                                                      ║"
echo "║   PostgreSQL is inside Docker — no external access   ║"
echo "║   JWT_SECRET: auto-generated (see backend/.env)      ║"
echo "║                                                      ║"
echo "║   Useful commands:                                   ║"
echo "║     docker compose logs -f backend                   ║"
echo "║     docker compose restart backend                   ║"
echo "║     docker compose down                              ║"
echo "║     docker compose up --build -d                     ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"
